### ISSUE TITLE
SNAPPY compression option in ParquetFile?? 

### ISSUE THREAD

**Issue by data-steve** [dask/fastparquet#142]
Tried reading in folder of parquet files but SNAPPY not allowed and tells me to choose another compression option. Where do I pass in the compression option for the read step? I see it for the write step, but not `ParquetFile`

```
from fastparquet import ParquetFile, writer

filelist = glob(data_path+"/*parquet")
filelist
['.../data/deleted_data/part-00000-ad202203-7b33-4afd-9702-21ec5edc91ea.snappy.parquet',
 '.../data/deleted_data/part-00001-ad202203-7b33-4afd-9702-21ec5edc91ea.snappy.parquet',
 '.../data/deleted_data/part-00002-ad202203-7b33-4afd-9702-21ec5edc91ea.snappy.parquet',
....]
```

Had to write a meta file

```
writer.merge(filelist[1:])
```

So again, I tried to read it in then but SNAPPY not allowed and tells me to choose another compression option. Where do I pass in the compression option for the read step? I see it for the write step, but not `ParquetFile`

```
df = ParquetFile(data_path+"/").to_pandas()


RuntimeErrorTraceback (most recent call last)
<ipython-input-71-0cf81b88c4e1> in <module>()
----> 1 df = ParquetFile(data_path+"/").to_pandas()

/Users/steve/anaconda/lib/python2.7/site-packages/fastparquet/api.pyc in to_pandas(self, columns, categories, filters, index, timestamp96)
    308                          for (name, v) in views.items()}
    309                 self.read_row_group_file(rg, columns, categories, index,
--> 310                                          assign=parts, timestamp96=timestamp96)
    311                 start += rg.num_rows
    312         return df

/Users/steve/anaconda/lib/python2.7/site-packages/fastparquet/api.pyc in read_row_group_file(self, rg, columns, categories, index, assign, timestamp96)
    136                 fn, rg, columns, categories, self.helper, self.cats,
    137                 open=self.open, selfmade=self.selfmade, index=index,
--> 138                 assign=assign, timestamp96=timestamp96)
    139         if ret:
    140             return df

/Users/steve/anaconda/lib/python2.7/site-packages/fastparquet/core.pyc in read_row_group_file(fn, rg, columns, categories, schema_helper, cats, open, selfmade, index, assign, timestamp96)
    266         return read_row_group(f, rg, columns, categories, schema_helper, cats,
    267                               selfmade=selfmade, index=index, assign=assign,
--> 268                               timestamp96=timestamp96)
    269 
    270 

/Users/steve/anaconda/lib/python2.7/site-packages/fastparquet/core.pyc in read_row_group(file, rg, columns, categories, schema_helper, cats, selfmade, index, assign, timestamp96)
    301         raise RuntimeError('Going with pre-allocation!')
    302     read_row_group_arrays(file, rg, columns, categories, schema_helper,
--> 303                           cats, selfmade, assign=assign, timestamp96=timestamp96)
    304 
    305     for cat in cats:

/Users/steve/anaconda/lib/python2.7/site-packages/fastparquet/core.pyc in read_row_group_arrays(file, rg, columns, categories, schema_helper, cats, selfmade, assign, timestamp96)
    290                  selfmade=selfmade, assign=out[name],
    291                  catdef=out[name+'-catdef'] if use else None,
--> 292                  timestamp96=mr)
    293 
    294 

/Users/steve/anaconda/lib/python2.7/site-packages/fastparquet/core.pyc in read_col(column, schema_helper, infile, use_cat, grab_dict, selfmade, assign, catdef, timestamp96)
    229             skip_nulls = False
    230         defi, rep, val = read_data_page(infile, schema_helper, ph, cmd,
--> 231                                         skip_nulls, selfmade=selfmade)
    232         d = ph.data_page_header.encoding == parquet_thrift.Encoding.PLAIN_DICTIONARY
    233         if use_cat and not d:

/Users/steve/anaconda/lib/python2.7/site-packages/fastparquet/core.pyc in read_data_page(f, helper, header, metadata, skip_nulls, selfmade)
     97     """
     98     daph = header.data_page_header
---> 99     raw_bytes = _read_page(f, header, metadata)
    100     io_obj = encoding.Numpy8(np.frombuffer(byte_buffer(raw_bytes),
    101                                            dtype=np.uint8))

/Users/steve/anaconda/lib/python2.7/site-packages/fastparquet/core.pyc in _read_page(file_obj, page_header, column_metadata)
     29     """Read the data page from the given file-object and convert it to raw, uncompressed bytes (if necessary)."""
     30     raw_bytes = file_obj.read(page_header.compressed_page_size)
---> 31     raw_bytes = decompress_data(raw_bytes, column_metadata.codec)
     32 
     33     assert len(raw_bytes) == page_header.uncompressed_page_size, \

/Users/steve/anaconda/lib/python2.7/site-packages/fastparquet/compression.pyc in decompress_data(data, algorithm)
     80     if algorithm.upper() not in decompressions:
     81         raise RuntimeError("Decompression '%s' not available.  Options: %s" %
---> 82                 (algorithm.upper(), sorted(decompressions)))
     83     return decompressions[algorithm.upper()](data)

RuntimeError: Decompression 'SNAPPY' not available.  Options: ['GZIP', 'UNCOMPRESSED']

```

Conda environment

```
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/steve/anaconda  (writable)
    default environment : /Users/steve/anaconda
       envs directories : /Users/steve/anaconda/envs
          package cache : /Users/steve/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

            conda list | grep fastparquet
fastparquet               0.0.5                    py27_1    conda-forge

```

**Comment by martindurant** [comment]
Do you have snappy installed?
You should try
```
conda install python-snappy
```

**Comment by data-steve** [comment]
Yes, when I got this error 

snappy                    1.1.4                         1    conda-forge

 I installed it because I saw it in your travis.yml. It doesn’t install as a dependency with fastparquet from condo-forge.

However, now that you mention it, I didn’t restart my python interpreter. And now that I do, it works 

I suck

~ Steve

Sent via telepathy

**Comment by data-steve** [comment]
however now I get these errors. (I restarted my interpreter again this time.)

when I try `import dask.dataframe as dd` I get

```
AttributeErrorTraceback (most recent call last)
<ipython-input-1-e012ff17e82a> in <module>()
----> 1 import dask.dataframe as dd

/Users/steve/anaconda/lib/python2.7/site-packages/dask/dataframe/__init__.py in <module>()
      3 from .core import (DataFrame, Series, Index, _Frame, map_partitions,
      4                    repartition, to_delayed, to_datetime)
----> 5 from .io import (from_array, from_pandas, from_bcolz,
      6                  from_dask_array, read_hdf, read_sql_table,
      7                  from_delayed, read_csv, to_csv, read_table,

/Users/steve/anaconda/lib/python2.7/site-packages/dask/dataframe/io/__init__.py in <module>()
      9 from . import demo
     10 try:
---> 11     from .parquet import read_parquet, to_parquet
     12 except ImportError:
     13     pass

/Users/steve/anaconda/lib/python2.7/site-packages/dask/dataframe/io/parquet.py in <module>()
    440 
    441 if pyarrow_parquet:
--> 442     @partial(normalize_token.register, pyarrow_parquet.ParquetDataset)
    443     def normalize_PyArrowParquetDataset(ds):
    444         return (type(ds), ds.paths)

AttributeError: 'module' object has no attribute 'ParquetDataset'
```

So then I restarted my interpreter again and did `import pyarrow` because I saw earlier that pyarrow just updated their API. (I'm also currently having trouble getting the new pyarrow to work on my ec2 instance.)

But anyway, then I do `import dask.dataframe as dd` again and now I get:

```
ImportErrorTraceback (most recent call last)
<ipython-input-3-8010029fbbe3> in <module>()
----> 1 import dask.dataframe

/Users/steve/anaconda/lib/python2.7/site-packages/dask/dataframe/__init__.py in <module>()
      3 from .core import (DataFrame, Series, Index, _Frame, map_partitions,
      4                    repartition, to_delayed, to_datetime)
----> 5 from .io import (from_array, from_pandas, from_bcolz,
      6                  from_dask_array, read_hdf, read_sql_table,
      7                  from_delayed, read_csv, to_csv, read_table,

/Users/steve/anaconda/lib/python2.7/site-packages/dask/dataframe/io/__init__.py in <module>()
      7 from .hdf import read_hdf, to_hdf
      8 from .sql import read_sql_table
----> 9 from . import demo
     10 try:
     11     from .parquet import read_parquet, to_parquet

ImportError: cannot import name demo
```

**Comment by data-steve** [comment]
whether I do `from dask.dataframe import read_parquet`  or even `from dask.dataframe import read_csv` I still get the same `cannot import name demo` import error

**Comment by mrocklin** [comment]
cc @wesm compatibility error from the recent pyarrow code

**Comment by wesm** [comment]
Looks like user is using an outdated version of pyarrow based on https://github.com/conda-forge/pyarrow-feedstock/issues/23. This is my fault -- I updated arrow-cpp and parquet-cpp a couple days ago but didn't get the pyarrow build through

```
$ python
Python 3.6.1 | packaged by conda-forge | (default, May  2 2017, 22:08:33) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wesm/anaconda3/envs/test-12/lib/python3.6/site-packages/pyarrow/__init__.py", line 28, in <module>
    import pyarrow._config
ImportError: /home/wesm/anaconda3/envs/test-12/lib/python3.6/site-packages/pyarrow/_config.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN5arrow2py9InitNumPyEv
```

I'm going to open a conda-forge update for pyarrow right now which should solve the problem. Final 0.3 release build should be out this weekend

**Comment by mrocklin** [comment]
Should we be checking versions in the pyarrow_parquet check?

**Comment by wesm** [comment]
We ought to be, yes

**Comment by data-steve** [comment]
Thanks all for responsiveness. 

Was conda-forge github the right place to post that pyarrow-specific issue?

**Comment by wesm** [comment]
Sure, definitely, since it was a packaging problem. We're going to be releasing a little more frequently going forward (this was 10 weeks between 0.2 and 0.3) so I am going to avoid posting .pre or .post builds unless it's something really time sensitive.

**Comment by mrocklin** [comment]
See https://github.com/dask/dask/pull/2295

**Comment by data-steve** [comment]
@martindurant and @mrocklin , I'm going to close out this issue because the snappy problem and the pyarrow problem are resolved. Thank you again to all 3 of you. 

But after updating with `conda install fastparquet pyarrow dask -c conda-forge` I still get errors with  `fastparquet` in `dask.dataframe.read_parquet` with `engine` as `auto` and `fastparquet`. I'll open a new issue and put in the details.

**Comment by BullzeyeBG** [comment]
> whether I do `from dask.dataframe import read_parquet` or even `from dask.dataframe import read_csv` I still get the same `cannot import name demo` import error



> Yes, when I got this error snappy 1.1.4 1 conda-forge I installed it because I saw it in your travis.yml. It doesn’t install as a dependency with fastparquet from condo-forge. However, now that you mention it, I didn’t restart my python interpreter. And now that I do, it works I suck ~ Steve Sent via telepathy
> […](#)
> On May 3, 2017, at 6:59 PM, Martin Durant ***@***.***> wrote: conda install python-snappy

Hey, lamers question - how do you restart the interpreter? I'm running into the same question as you do....

**Comment by michcio1234** [comment]
You just re-start python session or click a little ![image](https://user-images.githubusercontent.com/16254622/55550191-ef0bdc00-56d7-11e9-976c-ae61490bb725.png) icon in your notebook.
