### ISSUE TITLE
TypeError: bad argument type for built-in operation

### ISSUE THREAD

**Issue by gallamine** [dask/fastparquet#145]
I am trying to write my first parquet file. I have a very large text file (200,000 rows, ~200MB) that I've read into a Pandas dataframe. Shape is `(202363, 52)`.

When calling `fastparquet.write('./parquet-logs/out.parq', df, compression='GZIP')` I get the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-37-e28f2844674b> in <module>()
      1 # write data
----> 2 fastparquet.write('./parquet-logs/out.parq', df, compression='GZIP')

/Users/william/anaconda/envs/parquet-python/lib/python3.6/site-packages/fastparquet/writer.py in write(filename, data, row_group_offsets, compression, file_scheme, open_with, mkdirs, has_nulls, write_index, partition_on, fixed_text, append, object_encoding, times)
    801     if file_scheme == 'simple':
    802         write_simple(filename, data, fmd, row_group_offsets,
--> 803                      compression, open_with, has_nulls, append)
    804     elif file_scheme in ['hive', 'drill']:
    805         if append:

/Users/william/anaconda/envs/parquet-python/lib/python3.6/site-packages/fastparquet/writer.py in write_simple(fn, data, fmd, row_group_offsets, compression, open_with, has_nulls, append)
    701                    else None)
    702             rg = make_row_group(f, data[start:end], fmd.schema,
--> 703                                 compression=compression)
    704             if rg is not None:
    705                 fmd.row_groups.append(rg)

/Users/william/anaconda/envs/parquet-python/lib/python3.6/site-packages/fastparquet/writer.py in make_row_group(f, data, schema, compression)
    599                 comp = compression
    600             chunk = write_column(f, data[column.name], column,
--> 601                                  compression=comp)
    602             rg.columns.append(chunk)
    603     rg.total_byte_size = sum([c.meta_data.total_uncompressed_size for c in

/Users/william/anaconda/envs/parquet-python/lib/python3.6/site-packages/fastparquet/writer.py in write_column(f, data, selement, compression)
    514     start = f.tell()
    515     bdata = definition_data + repetition_data + encode[encoding](
--> 516             data, selement)
    517     bdata += 8 * b'\x00'
    518     try:

/Users/william/anaconda/envs/parquet-python/lib/python3.6/site-packages/fastparquet/writer.py in encode_plain(data, se)
    272 def encode_plain(data, se):
    273     """PLAIN encoding; returns byte representation"""
--> 274     out = convert(data, se)
    275     if se.type == parquet_thrift.Type.BYTE_ARRAY:
    276         return pack_byte_array(list(out))

/Users/william/anaconda/envs/parquet-python/lib/python3.6/site-packages/fastparquet/writer.py in convert(data, se)
    165     elif dtype == "O":
    166         if converted_type == parquet_thrift.ConvertedType.UTF8:
--> 167             out = array_encode_utf8(data)
    168         elif converted_type is None:
    169             if type in revmap:

/Users/william/anaconda/envs/parquet-python/lib/python3.6/site-packages/fastparquet/speedups.pyx in fastparquet.speedups.array_encode_utf8 (fastparquet/speedups.c:2094)()

TypeError: bad argument type for built-in operation
```

Before I start dividing up the file to find the exact line that's causing the problem, does anyone recognize this as a known error or what could be causing it?

I am using version `0.0.6` of fastparquet.

**Comment by martindurant** [comment]
The error appears to say that fastparquet is trying to convert values of a string column into bytes for storage. Unless you specify the encoding for "object" type columns, fastparquet tries to guess from the first ten valid values in the column. It seems that in this case, some of one of your columns is string, and some is some other value.
You can specify how you would like to encode your object columns, and in this case perhaps JSON would be a good choice (although slower); or you could investigate your data in case this is being caused by some errant value that should not be stored. It is hard to be more specific without access to the data - if you can generate a self-contained example with some subsection, I could probably say more.

**Comment by tweeter0830** [comment]
I have this problem as well. My data is all strings.

```
ipdb> l
    163             out = data.values
    164     elif "S" in str(dtype)[:2] or "U" in str(dtype)[:2]:
    165         out = data.values
    166     elif dtype == "O":
    167         if converted_type == parquet_thrift.ConvertedType.UTF8:
--> 168             out = array_encode_utf8(data)
    169         elif converted_type is None:
    170             if type in revmap:
    171                 out = data.values.astype(revmap[type], copy=False)
    172             elif type == parquet_thrift.Type.BOOLEAN:
    173                 padded = np.lib.pad(data.values, (0, 8 - (len(data) % 8)),

ipdb> data
0          ZUOXSXVGDKUE4IP
...
Name: chunk_id, Length: 2646000, dtype: object

ipdb> set(data)
set(['ZUOXSXVGDKUE4IP'])
```

**Comment by martindurant** [comment]
@tweeter0830 : are you on python2 by any chance? If that is so, then your apparent string is actually a bytestring, and you want to use object encoding "bytes".

In python2:

    df = pd.DataFrame({'col': ['a']})   # equivalent to b'a' in py3
    fastparquet.write('a.parq', df, object_encoding='utf8')   # <- give the error
    fastparquet.write('a.parq', df, object_encoding='bytes')  # OK

    df = pd.DataFrame({'col': [u'a']})   # equivalent to 'a' in py3
    fastparquet.write('a.parq', df, object_encoding='utf8')   # OK
    fastparquet.write('a.parq', df, object_encoding='bytes')  # gives a different error

**Comment by gowtham-sai** [comment]
Hi @martindurant , 

The error trace is somewhat hard to guess which columns is causing that issue. Can you add more details to the error trace. The following is the error trace below. 


```python
 Traceback (most recent call last):
  File "/srv/vtap/s3syncer.py", line 213, in vtap
    process(processing_file)
  File "/srv/vtap/s3syncer.py", line 197, in process
    write_parquet(df, s3path, opener=s3open)
  File "/srv/vtap/s3syncer.py", line 145, in write_parquet
    append=False, write_index=True, has_nulls=True)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 788, in write
    compression, open_with, has_nulls, append)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 684, in write_simple
    compression=compression)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 580, in make_row_group
    compression=comp)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 486, in write_column
    data, selement)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 238, in encode_plain
    out = convert(data, se)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 167, in convert
    out = array_encode_utf8(data)
  File "fastparquet/speedups.pyx", line 60, in fastparquet.speedups.array_encode_utf8
    result[i] = PyUnicode_AsUTF8String(arr[i])
TypeError: bad argument type for built-in operation

```
How about adding the column name which causing the error to the error trace?

**Comment by martindurant** [comment]
Yes, this has happened often enough that it's a reasonable request to provide a clearer error message, with details such as the column causing the problem.

**Comment by gowtham-sai** [comment]
@martindurant  shall we reopen this just to track the above mentioned request?

**Comment by martindurant** [comment]
I'll aim to do it tomorrow, so there should be no need.

**Comment by gowtham-sai** [comment]
Awesome. Thanks. Just keep us update, once it is done.

**Comment by martindurant** [comment]
Done

**Comment by gowtham-sai** [comment]
yep, thanks :)
