### ISSUE TITLE
"The truth value of a Index is ambiguous" thrown by pandas off of fastparquet api.py

### ISSUE THREAD

**Issue by javadba** [dask/fastparquet#172]
Scenario:  opening a snappy compressed parquet file with two columns and no index.

Following line of `fastparquet/api.py` sometimes (i do not understand what conditions cause it) makes pandas unhappy

        columns = columns or self.columns

Here is the result:

Connected to pydev debugger (build 171.4694.23)
Traceback (most recent call last):
  File "/Users/sboesch/Library/Application Support/IntelliJIdea2017.1/python/helpers/pydev/pydevd.py", line 1591, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/Users/sboesch/Library/Application Support/IntelliJIdea2017.1/python/helpers/pydev/pydevd.py", line 1018, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/git/fantests/src/python/parquet.py", line 4, in <module>
    df2 = pf.to_pandas(df.columns, categories=df.columns[0])
  File "/usr/local/lib/python2.7/site-packages/fastparquet/api.py", line 379, in to_pandas
    columns = columns or self.columns
  File "/usr/local/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 1622, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Index is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by martindurant** [comment]
What is `df.columns` in this case? The docstring suggests you should pass a list if you want to select columns, and passing a pandas Series or array is not tested. You could do `list(df.columns)` and it will probably work.

**Comment by javadba** [comment]
OK i see :  the `df.columns` is actually an `index`.  Along the lines of your comment what does work is `df.columns.values.tolist()` . This issue can be closed.
