### ISSUE TITLE
Commit 8d45042 can't read a file written by commit 5d598ac if it has lists encoded with object_encoding='json'

### ISSUE THREAD

**Issue by jdanbrown** [dask/fastparquet#185]
- We're running into a `dd.read_parquet` error when trying to upgrade from 5d598ac to 8d45042
  - Diff: https://github.com/dask/fastparquet/compare/5d598ac...8d45042
- Rewriting all of our parquet files with the newer code (8d45042) would solve it, but would be painful...

## Repro
```py
import pandas as pd
import dask.dataframe as dd

# Make a ddf with an array col, and write it as json
ddf = dd.from_pandas(pd.DataFrame(dict(a=[1,2],b=[3,4],c=[[5,6],[]])), npartitions=1)
object_encoding = {'c': 'json'}

# Install old version (5d598ac) and write
ddf.to_parquet(
    's3://.../fastparquet-compat-5d598ac.parquet.snappy',
    object_encoding=object_encoding,
    compression='snappy',
)

# Install new version (8d45042) and write
ddf.to_parquet(
    's3://.../fastparquet-compat-8d45042.parquet.snappy',
    object_encoding=object_encoding,
    compression='snappy',
)

# Reading new files works in both old (5d598ac) and new (8d45042)
dd.read_parquet('s3://.../fastparquet-compat-8d45042.parquet.snappy')

# Reading old files works in old (5d598ac) but not new (8d45042)
dd.read_parquet('s3://.../fastparquet-compat-5d598ac.parquet.snappy')

>>> dd.read_parquet('s3://opendoor-user/danbrown/junk-0.parquet.snappy')
Traceback (most recent call last):
  File "<ipython-input-1-5329056c2873>", line 1, in <module>
    dd.read_parquet('s3://opendoor-user/danbrown/fastparquet-compat-5d598ac.parquet.snappy')
  File "/Users/danb/miniconda3/envs/signals/lib/python3.6/site-packages/dask/dataframe/io/parquet.py", line 291, in read_parquet
    categories=categories, index=index)
  File "/Users/danb/miniconda3/envs/signals/lib/python3.6/site-packages/dask/dataframe/io/parquet.py", line 116, in _read_fastparquet
    minmax = fastparquet.api.sorted_partitioned_columns(pf)
  File "/Users/danb/miniconda3/envs/signals/lib/python3.6/site-packages/fastparquet/api.py", line 656, in sorted_partitioned_columns
    s = statistics(pf)
  File "/Users/danb/miniconda3/envs/signals/lib/python3.6/site-packages/fastparquet/api.py", line 629, in statistics
    np.array(d[name][column]), se))
  File "/Users/danb/miniconda3/envs/signals/lib/python3.6/site-packages/fastparquet/converted_types.py", line 163, in convert
    out[:] = [json.loads(d.decode('utf8')) for d in data]
  File "/Users/danb/miniconda3/envs/signals/lib/python3.6/site-packages/fastparquet/converted_types.py", line 163, in <listcomp>
    out[:] = [json.loads(d.decode('utf8')) for d in data]
  File "/Users/danb/miniconda3/envs/signals/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/danb/miniconda3/envs/signals/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/danb/miniconda3/envs/signals/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
JSONDecodeError: Expecting value
```

Here's an ipython `Verbose` traceback:
```py
---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-1-5329056c2873> in <module>()
----> 1 dd.read_parquet('s3://opendoor-user/danbrown/fastparquet-compat-5d598ac.parquet.snappy')
        global dd.read_parquet = <function read_parquet at 0x117e2d840>

/Users/danb/miniconda3/envs/signals/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in read_parquet(path='s3://opendoor-user/danbrown/fastparquet-compat-5d598ac.parquet.snappy', columns=None, filters=None, categories=None, index=None, storage_options=None, engine='fastparquet')
    289         return _read_fastparquet(fs, paths, file_opener, columns=columns,
    290                                  filters=filters,
--> 291                                  categories=categories, index=index)
        categories = None
        index = None
    292     else:
    293         return _read_pyarrow(fs, paths, file_opener, columns=columns,

/Users/danb/miniconda3/envs/signals/lib/python3.6/site-packages/dask/dataframe/io/parquet.py in _read_fastparquet(fs=<dask.bytes.s3.DaskS3FileSystem object>, paths=['s3://opendoor-user/danbrown/fastparquet-compat-5d598ac.parquet.snappy'], myopen=<dask.bytes.core.OpenFileCreator object>, columns=None, filters=[], categories={}, index=None, storage_options=None)
    114
    115     if index_col:
--> 116         minmax = fastparquet.api.sorted_partitioned_columns(pf)
        minmax = undefined
        global fastparquet.api.sorted_partitioned_columns = <function sorted_partitioned_columns at 0x117e25c80>
        global pf = undefined
    117         if index_col in minmax:
    118             divisions = (list(minmax[index_col]['min']) +

/Users/danb/miniconda3/envs/signals/lib/python3.6/site-packages/fastparquet/api.py in sorted_partitioned_columns(pf=<Parquet File: {'name': 's3://opendoor-user/danb...x', 'a', 'b', 'c'], 'partitions': [], 'rows': 2}>)
    654     statistics
    655     """
--> 656     s = statistics(pf)
        s = undefined
        global statistics = <function statistics at 0x117e25bf8>
        pf = <Parquet File: {'name': 's3://opendoor-user/danbrown/fastparquet-compat-5d598ac.parquet.snappy/_metadata', 'columns': ['index', 'a', 'b', 'c'], 'partitions': [], 'rows': 2}>
    657     columns = pf.columns
    658     out = dict()

/Users/danb/miniconda3/envs/signals/lib/python3.6/site-packages/fastparquet/api.py in statistics(obj=<Parquet File: {'name': 's3://opendoor-user/danb...x', 'a', 'b', 'c'], 'partitions': [], 'rows': 2}>)
    627                             or None in d[name][column]
    628                             else list(converted_types.convert(
--> 629                                 np.array(d[name][column]), se))
        global np.array = <built-in function array>
        d = {'min': {'index': [0], 'a': [1], 'b': [3], 'c': [b'\x02\x00\x00\x00[]']}, 'max': {'index': [1], 'a': [2], 'b': [4], 'c': [b'\x06\x00\x00\x00[5, 6]']}, 'null_count': {'index': [0], 'a': [0], 'b': [0], 'c': [0]}, 'distinct_count': {'index': [None], 'a': [None], 'b': [None], 'c': [None]}}
        name = 'min'
        column = 'c'
        se = <class 'parquet_thrift.SchemaElement'>
converted_type: 19
field_id: None
name: c
num_children: None
precision: None
repetition_type: 1
scale: None
type: 6
type_length: None

    630                         )
    631                     except KeyError:

/Users/danb/miniconda3/envs/signals/lib/python3.6/site-packages/fastparquet/converted_types.py in convert(data=array([b'\x02\x00\x00\x00[]'],
      dtype='|S6'), se=<class 'parquet_thrift.SchemaElement'>
converted...on_type: 1
scale: None
type: 6
type_length: None
, timestamp96=True)
    161         else:
    162             out = data
--> 163         out[:] = [json.loads(d.decode('utf8')) for d in data]
        out = array([None], dtype=object)
        global json.loads = <function loads at 0x10a367d90>
        global d.decode = undefined
        global d = undefined
        data = array([b'\x02\x00\x00\x00[]'],
      dtype='|S6')
    164         return out
    165     elif ctype == parquet_thrift.ConvertedType.BSON:

/Users/danb/miniconda3/envs/signals/lib/python3.6/site-packages/fastparquet/converted_types.py in <listcomp>(.0=<iterator object>)
    161         else:
    162             out = data
--> 163         out[:] = [json.loads(d.decode('utf8')) for d in data]
        global out = undefined
        global json.loads = <function loads at 0x10a367d90>
        d.decode = <built-in method decode of numpy.bytes_ object at 0x11ab8b930>
        d = b'\x02\x00\x00\x00[]'
        global data = undefined
    164         return out
    165     elif ctype == parquet_thrift.ConvertedType.BSON:

/Users/danb/miniconda3/envs/signals/lib/python3.6/json/__init__.py in loads(s='\x02\x00\x00\x00[]', encoding=None, cls=None, object_hook=None, parse_float=None, parse_int=None, parse_constant=None, object_pairs_hook=None, **kw={})
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
        global _default_decoder.decode = <bound method JSONDecoder.decode of <json.decoder.JSONDecoder object at 0x10a36a4e0>>
        s = '\x02\x00\x00\x00[]'
    355     if cls is None:
    356         cls = JSONDecoder

/Users/danb/miniconda3/envs/signals/lib/python3.6/json/decoder.py in decode(self=<json.decoder.JSONDecoder object>, s='\x02\x00\x00\x00[]', _w=<built-in method match of _sre.SRE_Pattern object>)
    337
    338         """
--> 339         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
        obj = undefined
        end = undefined
        self.raw_decode = <bound method JSONDecoder.raw_decode of <json.decoder.JSONDecoder object at 0x10a36a4e0>>
        s = '\x02\x00\x00\x00[]'
        global idx = undefined
        _w = <built-in method match of _sre.SRE_Pattern object at 0x10a245c30>
        s.end = undefined
    340         end = _w(s, end).end()
    341         if end != len(s):

/Users/danb/miniconda3/envs/signals/lib/python3.6/json/decoder.py in raw_decode(self=<json.decoder.JSONDecoder object>, s='\x02\x00\x00\x00[]', idx=0)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
        global JSONDecodeError = <class 'json.decoder.JSONDecodeError'>
        s = '\x02\x00\x00\x00[]'
        err.value = undefined
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## Versions
```sh
$ python --version
Python 3.6.0

$ cat requirements.txt | egrep 'dask/(dask|fastparquet)' | grep -v '^#'
git+https://github.com/dask/dask.git@00ed56e
git+https://github.com/dask/fastparquet.git@5d598ac
```

**Comment by martindurant** [comment]
I'll look into it and expect you shouldn't have to rewrite your data. For JSON encoded data, there shouldn't be any column max/min values anyway.

**Comment by jdanbrown** [comment]
🎉 Thanks!
