### ISSUE TITLE
Issues whlie reading the parquet file ? Seek before start of file?

### ISSUE THREAD

**Issue by gowtham-sai** [dask/fastparquet#203]
I've parquet files written by fast parquet to s3. I'm getting the following error while reading those files from s3. Here is the error trace: 

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/api.py", line 99, in __init__
    self._parse_header(f, verify)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/api.py", line 122, in _parse_header
    f.seek(-(head_size+8), 2)
  File "/usr/local/lib/python2.7/dist-packages/s3fs/core.py", line 1004, in seek
    raise ValueError('Seek before start of file')
ValueError: Seek before start of file
```

[Here is the Parquet File](https://s3-ap-southeast-1.amazonaws.com/vtap-sync/vnk/yr%3D2017/mn%3D08/dt%3D28/events_pSsEABrKRDWl__0JRpCkrQ.parquet)

What is the root cause of this issue? How can we avoid this?

**Comment by gowtham-sai** [comment]
Corrupted parquet file, nothing to do with FastParquet.
