### ISSUE TITLE
Memory Keep Increasing 

### ISSUE THREAD

**Issue by gowtham-sai** [dask/fastparquet#204]
Is there anything wrong with the following code? My Memory keep increasing and machine rebooting because of auto healing. I've 16GB Machine. I'm reading just 500 Mb. Something is terribly wrong., I guess. 

```
#!/usr/bin/python

import os
import sys
import uuid
import time
import base64
import requests
import s3fs
import fastparquet
import glob
import vtap_cols
import datetime

import pandas as pd
import numpy as np
import ujson as json

start_time = time.time()

key = 'AKIAJ'
secret = 'IX9sRERZ'

fs = s3fs.S3FileSystem(key=key, secret=secret)
s3open = fs.open

filelist = glob.glob('/vol/vtap-sync/vnk/*/*/*/*/events.json')

# get a UUID - URL safe, Base64
def get_a_uuid():
r_uuid = base64.urlsafe_b64encode(uuid.uuid4().bytes)
return r_uuid.replace('=', '')

def flatten(event_data):
    return pd.DataFrame(event_data).set_index('key').squeeze()

def flat(x):
	return dict([(list(d.values())[1], list(d.values())[0]) for d in x])

def get_cols_map(cols):
    default_cols = vtap_cols.columns_to_replace.keys()
    correct_cols_map = {}
    for col in cols:
	    if col in default_cols:
    		correct_cols_map[col] = vtap_cols.columns_to_replace[col]
    return correct_cols_map

for file in filelist:
    filedate = datetime.datetime.utcfromtimestamp(os.stat(file).st_mtime)
    curdate = datetime.datetime.now()
    print filedate, curdate, curdate-filedate
    if (curdate - filedate).total_seconds() > 5400:
	
        parts = file.split('/')
        parts[4] = 'yr='+ parts[4]
        parts[5] = 'mn='+ parts[5]
        parts[6] = 'dt='+ parts[6]
        idx = parts.index('vtap-sync')
        newfile = ('/'.join(parts[idx:idx+5] ) + '/proc.json').strip('/')
        moved_file = file.replace('events.json', 'proc.json')
        print "[+] Processing File %s"%file
        try:
            os.rename(file, moved_file)
            left_over_events = ''
            has_next = True
            with open(moved_file, 'r') as events:
                while has_next:
                    buf = events.read(536870912)
                    if buf:
                        left_over_events += buf
                        left_parts = left_over_events.split('\n')
                        events_data = left_parts[:-1]
                        left_over_events = left_parts[-1]
                        jevents_data = '[' + ','.join(events_data) + ']'
                        df = pd.read_json(jevents_data)
                        event_data = pd.io.json.json_normalize(df['event_data'].apply(flat).tolist())
                        df = df.drop('event_data', axis=1)
                        df = df.join(event_data)
                        df.replace('[Rs. ]','',regex=True, inplace=True)
                        cls_to_replace = [column for column in df.columns if 'total' in column]
                        df[cls_to_replace] = df[cls_to_replace].apply(pd.to_numeric, errors='coerce')
                        # df.rename(columns=get_cols_map(df.columns), inplace=True)
                        parquet_filename = newfile.replace('proc.json', 'events_'+get_a_uuid()+'.parquet')
                        fastparquet.write(parquet_filename, df, row_group_offsets=5000000, compression='GZIP',file_scheme='simple', append=False, write_index=True, has_nulls=True, open_with=s3open)
                    else: has_next = False
        except Exception as e:
            if os.path.isfile(moved_file):
                os.rename(moved_file, file)
            print e
            requests.post('https://api.flock.com/hooks/sendMessage/ab430c0d-2ed9-4226-84ff-f803245a0e05', json={'text': "Error while processing file %s and error is %s"%(file,e)})
        print "[+] Processing Done %s"%file
	
end_time = time.time()

requests.post('https://api.flock.com/hooks/sendMessage/3dcf9001-9dc8a2d57a1b', json={'text': "Proccessed %s. Time Taken: %s"%(len(filelist), end_time-start_time)})
requests.post('https://api.flock.com/hooks/sendMessage/ab430c0d-f803245a0e05', json={'text': "Proccessed %s. Time Taken: %s"%(len(filelist), end_time-start_time)})


```

**Comment by martindurant** [comment]
xref #203 
It is not obvious from the above what might be going on. Note that the file does appear corrupted (i.e., this is not an S3 issue). Writing appears to have stopped without generating a metadata footer at all. I assume that if an exception occurs, the data from the try block is being kept in memory.
Can you reproduce the issue with a bite-size amount of input data which you can upload, so that I can try to debug?

Do you get any error messages while the code above runs? What are the data types and contents of your columns like? What versions of fastparquet and pandas are you using?

**Comment by gowtham-sai** [comment]
@martindurant brilliant. I guess I got the issue. `if an exception occurs, the data from the try block is being kept in memory`. Yep this is the cause of the problem.  Every time I run the script, often there will be few issues related to some columns. I guess that's what causing the issue. Ideally I could put the try block in side with open and then make all other variable globals and make them None if exception throws up. 

But, this couldn't be the reason for issue #203 . Because all the exceptions which I got are related to  pandas columns renaming or something else except this one. `bad argument type for built-in operation`. This alone, I don't know what the issue is about.  

I assume, there wont be any issue while writing to s3 as it is from the same region server to same region bucket.

**Comment by gowtham-sai** [comment]
`bad argument type for built-in operation` Here is the traceback for that, It looks like, it is from fastparquet. I guess those files are corrupted because of this. Traceback (most recent call last):

```python
  File "./s3sync.py", line 86, in <module>
    fastparquet.write(parquet_filename, df, row_group_offsets=5000000, compression='GZIP',file_scheme='simple', append=False, write_index=True, has_nulls=True, open_with=s3open)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 788, in write
    compression, open_with, has_nulls, append)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 684, in write_simple
    compression=compression)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 580, in make_row_group
    compression=comp)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 486, in write_column
    data, selement)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 238, in encode_plain
    out = convert(data, se)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 167, in convert
    out = array_encode_utf8(data)
  File "fastparquet/speedups.pyx", line 60, in fastparquet.speedups.array_encode_utf8
    result[i] = PyUnicode_AsUTF8String(arr[i])
TypeError: bad argument type for built-in operation
```

**Comment by gowtham-sai** [comment]
Looks like issue with #145. I'm using python 2.7.

I've attached sample [JSON](https://gist.github.com/gowtham-sai/86f26d1b14c99ffa4a339a0bb9229e5b) (it is not the one which throws error. But just for idea how the sample data looks like). 

Does this means, I've lists in my JSON? 
Setting up the `object_encoding = 'bytes'` will slove the issues?

**Comment by gowtham-sai** [comment]
Looks like issue with #145. I'm using python 2.7.

I've attached sample [JSON](https://gist.github.com/gowtham-sai/86f26d1b14c99ffa4a339a0bb9229e5b) (it is not the one which throws error. But just for idea how the sample data looks like). 

Does this means, I've lists in my JSON? 
Setting up the `object_encoding = 'bytes'` will slove the issues?

**Comment by gowtham-sai** [comment]
Why this is set to object. This is always integers. 

```python
Error while processing file /vol/vtap-sync/vnk/2017/08/26/06/events.json and error is Can't infer object conversion type: 0    5369834
1    3247096
2    6793759
3    5386575
4    6793759
5    6793759
6    6656674
7    3247091
8    5010378
9    6793759
Name: product_id, dtype: object and stack trace is Traceback (most recent call last):
  File "/srv/vtap/s3sync.py", line 92, in <module>
    fastparquet.write(parquet_filename, df, row_group_offsets=5000000, compression='GZIP',file_scheme='simple', append=False, write_index=True, has_nulls=True, open_with=s3open)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 784, in write
    times=times, index_cols=index_cols)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 645, in make_metadata
    object_encoding=oencoding, times=times)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 91, in find_type
    object_encoding = infer_object_encoding(data)
  File "/usr/local/lib/python2.7/dist-packages/fastparquet/writer.py", line 224, in infer_object_encoding
    raise ValueError("Can't infer object conversion type: %s" % head)
ValueError: Can't infer object conversion type: 0    5369834
1    3247096
2    6793759
3    5386575
4    6793759
5    6793759
6    6656674
7    3247091
8    5010378
9    6793759
Name: product_id, dtype: object

```

**Comment by martindurant** [comment]
In your JSON, the product_id is actually string every time, even if it happens to contain integers. The default thing for fastparquet to do with strings is to UTF8-encode them into writable bytes.
The error probably comes from some entry where the number is not quoted, but given as a true JSON integer.
Since you want this column to be integer, which represents the true nature of the data, and will give much better performance, you should explicitly describe the column as int on load (see the pandas docs) or convert in the final dataframe:

    df['product_id'] = df['product_id'].astype(int)

If there are values that cannot be converted, you will get an error here and have to decide how to cope with them.

Note furthermore, that `fastparquet.write` includes a parameter `object_encoding` with which you can specify what the contents of object columns should be interpreted as. In the case of integers, it effectively makes the same conversion as above, although it also allows for None values (i.e., if you read the same column back, you would get object type, containing integers and None)

    fastparquet.write(parquet_filename, df, row_group_offsets=5000000, compression='GZIP',file_scheme='simple', append=False, write_index=True, has_nulls=True, open_with=s3open, object_encoding={'product_id': 'int'})

**Comment by gowtham-sai** [comment]
Hey @martindurant , 

Sorry for not updating it. I've updated the script. And setting product_id type to int wont work here. As it NA (or NAN in some places). so, you need to do 

```python
df['product_id'] = df['product_id'].apply(pd.to_numeric, errors='coerce')
```


But this is not solving the issue. I've updated python script even to catch the errors and del the variable if none set and stop processing it.  Here is the below script. 


```python
#!/usr/bin/python

import os
import sys
import uuid
import time
import base64
import requests
import s3fs
import traceback
import fastparquet
import glob
import vtap_cols
import datetime

import pandas as pd
import numpy as np
import ujson as json

FLOAT_COLUMNS = ['product_id']

start_time = time.time()
file_count = 0

key = 'AK'
secret = 'IX9'

fs = s3fs.S3FileSystem(key=key, secret=secret)
s3open = fs.open

filelist = glob.glob('/vol/vtap-sync/vnk/*/*/*/*/events.json')

# get a UUID - URL safe, Base64
def get_a_uuid():
    r_uuid = base64.urlsafe_b64encode(uuid.uuid4().bytes)
    return r_uuid.replace('=', '')

def flatten(event_data):
    return pd.DataFrame(event_data).set_index('key').squeeze()

def flat(x):
	 return dict([(list(d.values())[1], list(d.values())[0]) for d in x])

def get_cols_map(cols):
	default_cols = vtap_cols.columns_to_replace.keys()
	correct_cols_map = {}
	for col in cols:
		if col in default_cols:
			correct_cols_map[col] = vtap_cols.columns_to_replace[col]
	return correct_cols_map

for file in filelist:
	filedate = datetime.datetime.utcfromtimestamp(os.stat(file).st_mtime)
	curdate = datetime.datetime.now()
	print filedate, curdate, curdate-filedate
	if (curdate - filedate).total_seconds() > 5400:
		file_count += 1
		parts = file.split('/')
		parts[4] = 'yr='+ parts[4]
		parts[5] = 'mn='+ parts[5]
		parts[6] = 'dt='+ parts[6]
		idx = parts.index('vtap-sync')
		newfile = ('/'.join(parts[idx:idx+5] ) + '/proc.json').strip('/')
		moved_file = file.replace('events.json', 'proc.json')
		print "[+] Processing File %s"%file

		os.rename(file, moved_file)
		left_over_events = ''
		has_next = True
		with open(moved_file, 'r') as events:
			while has_next:
				df = None
				jevents_data = None
				event_data = None
				cls_to_replace = None
				buf = None
				try: 
					buf = events.read(536870912)
					if buf:
						left_over_events += buf
						left_parts = left_over_events.split('\n')
						events_data = left_parts[:-1]
						left_over_events = left_parts[-1]
						jevents_data = '[' + ','.join(events_data) + ']'
						df = pd.read_json(jevents_data)
						event_data = pd.io.json.json_normalize(df['event_data'].apply(flat).tolist())
						df.drop('event_data', axis=1, inplace=True)
						df = df.join(event_data)
						df.replace('[Rs. ]','',regex=True, inplace=True)
						cls_to_replace = [column for column in df.columns if 'total' in column or column in FLOAT_COLUMNS]
						df[cls_to_replace] = df[cls_to_replace].apply(pd.to_numeric, errors='coerce')
						# df.rename(columns=get_cols_map(df.columns), inplace=True)
						parquet_filename = newfile.replace('proc.json', 'events_'+get_a_uuid()+'.parquet')
						fastparquet.write(parquet_filename, df, row_group_offsets=5000000, compression='GZIP',file_scheme='simple', append=False, write_index=True, has_nulls=True, open_with=s3open)
						del df
						del jevents_data
						del event_data
						del cls_to_replace
					else:
							has_next = False
				except Exception as e:
					del df
					del jevents_data
					del event_data
					del cls_to_replace
					del buf
					has_next = False
					callee = traceback.format_exc()
					if os.path.isfile(moved_file):
						os.rename(moved_file, file)
					print e
					requests.post('https://api.flock.com/hooks/sendMessage/ab430c0d-f803245a0e05', json={'text': "Error while processing file %s and error is %s and stack trace is %s"%(file,e, callee)})
		print "[+] Processing Done %s"%file
		
end_time = time.time()

requests.post('https://api.flock.com/hooks/sendMessage/3dcf9001-9dc8a2d57a1b', json={'text': "Proccessed %s. Time Taken: %s"%(file_count, end_time-start_time)})
requests.post('https://api.flock.com/hooks/sendMessage/ab430c0d-f803245a0e05', json={'text': "Proccessed %s. Time Taken: %s"%(file_count, end_time-start_time)})

```

My file size is 5GB. The first and direct error i'm getting is `Memory Error`. Here is the error stack: 

```python
[30/08/2017 11:22 PM] VTAP Production Bot: Proccessed 1. Time Taken: 130.516367912

[30/08/2017 11:32 PM] VTAP Production Bot: Error while processing file /vol/vtap-sync/vnk/2017/08/29/04/events.json and error is  and stack trace is Traceback (most recent call last):
  File "/srv/vtap/s3sync.py", line 89, in <module>
    df.replace('[Rs. ]','',regex=True, inplace=True)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 3789, in replace
    self._consolidate_inplace()
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 3138, in _consolidate_inplace
    self._protect_consolidate(f)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 3127, in _protect_consolidate
    result = f()
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/generic.py", line 3136, in f
    self._data = self._data.consolidate()
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 3573, in consolidate
    bm._consolidate_inplace()
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 3578, in _consolidate_inplace
    self.blocks = tuple(_consolidate(self.blocks))
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 4525, in _consolidate
    _can_consolidate=_can_consolidate)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 4545, in _merge_blocks
    new_values = _vstack([b.values for b in blocks], dtype)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/internals.py", line 4591, in _vstack
    return np.vstack(to_stack)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 237, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
MemoryError
```

It is happening at line number line number 89. Which is replace of values of a particular column total. So, I moved del event_data to above line 89. Which is not a good fix but a hack. 

Do you suggest any other thing? Any idea, why it is keep increasing and what it is the better way to deal with this data ?

**Comment by martindurant** [comment]
First, I would certainly more the processing within the try block into a function, which will do a better job of releasing memory each time you write some parquet. 
In your particular example, you are also capturing `e` and variables derived from it, which may well hose on to references to `e` and any variables in the stack. These are all global variables, so you would be best to have that in a function too. This is good general policy, don't have any function do too much:

    def process(filelist):
         for fn in filelist:
            make_file_names
            process(fn)

    def process(fn):
        with open(fn) as f:
            while ...:
                buf = f.read
                left_over
                to_parquet(events_data, outfile)

    def to_parquet(events_data, outfile):
        try:
            df = do_stuff
            fastparquet.write(outfile, df)
        except Exception as e:
            print(...)

Furthermore, if `buf` is 500MB, when you do `left_over_events += buf`, you will temporarily at least duplicate that number, and you then split, amend and join again before passing to pandas. Each of the variables `buf`, `left_parts`, `events_data`, `jevents_data`, `df`, `event_data` are at least that size, order-of-magnitude - do you need them all?? -, and there will be temporary copies too, especially when swapping around pandas columns. I recommend you try `memory_profiler`.

**Comment by martindurant** [comment]
In any case, this does not appear to be a fastparquet issue - OK to close?

**Comment by gowtham-sai** [comment]
@martindurant Yes, it's not fastparquet issue definitely. Yep, thanks for the suggestions and bearing with me. 

I'm closing the issue. Once again, thank you :)

**Comment by martindurant** [comment]
You are welcome.
