### ISSUE TITLE
Reading multiple Parquet files from S3

### ISSUE THREAD

**Issue by vcapelca** [dask/fastparquet#207]
Hi there,

I'm having issues reading multiple Parquet files on S3 on a single ParquetFile object. I use the s3fs lib (http://s3fs.readthedocs.io/en/latest/) to read from multiple S3 paths, get a Dataframe object, then write the result on a CSV file also on S3, like this:

```
import s3fs
import fastparquet as fp

s3 = s3fs.S3FileSystem()
fs = s3fs.core.S3FileSystem()

all_paths_from_s3 = fs.glob(path=s3_path)
myopen = s3.open
fp_obj = fp.ParquetFile(all_paths_from_s3,open_with=myopen)

df = fp_obj.to_pandas()
bytes_to_write = df.to_csv(None, encoding='utf-8', header = 'true', index = 'false')
with fs.open(csv_file_path, 'wb') as file:
  file.write(bytes_to_write)
```
Where s3_path = data-bi-swamp-dev/events/test/followers/dt=2017082*/*.parquet

This is how the fp_obj object looks when instantiated:
```
['data-bi-swamp dev/events/test/followers/dt=20170820/ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyMC8=.parquet', 'data-bi-swamp-dev/events/test/followers/dt=20170821/ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyMS8=.parquet', 'data-bi-swamp-dev/events/test/followers/dt=20170822/ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyMi8=.parquet', 'data-bi-swamp-dev/events/test/followers/dt=20170823/ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyMy8=.parquet', 'data-bi-swamp-dev/events/test/followers/dt=20170824/ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyNC8=.parquet', 'data-bi-swamp-dev/events/test/followers/dt=20170825/ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyNS8=.parquet', 'data-bi-swamp-dev/events/test/followers/dt=20170826/ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyNi8=.parquet', 'data-bi-swamp-dev/events/test/followers/dt=20170827/ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyNy8=.parquet', 'data-bi-swamp-dev/events/test/followers/dt=20170828/ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyOC8=.parquet', 'data-bi-swamp-dev/events/test/followers/dt=20170829/ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyOS8=.parquet']
```

And there is more info with fp_obj.info:
```
<Parquet File: {u'rows': 19581, u'name': u'data-bi-swamp-dev/events/test/followers/_metadata', u'columns': [u'published', u'verb', u'__embedded.followedId', u'__embedded.followerId', u'__embedded.since', u'actor.id', u'actor.objectType', u'target.id', u'target.objectType'], u'partitions': ['ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyMS8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyNi8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyNC8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyOS8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyMi8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyMC8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyNy8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyNS8', 'dt', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyOC8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyMy8']}>
{u'rows': 19581, u'name': u'data-bi-swamp-dev/events/test/followers/_metadata', u'columns': [u'published', u'verb', u'__embedded.followedId', u'__embedded.followerId', u'__embedded.since', u'actor.id', u'actor.objectType', u'target.id', u'target.objectType'], u'partitions': ['ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyMS8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyNi8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyNC8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyOS8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyMi8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyMC8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyNy8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyNS8', 'dt', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyOC8', 'ZXZlbnRzL3ZpYmJvL2ZvbGxvd2Vycy9kdD0yMDE3MDgyMy8']}
```

The issue appears when I want to convert that ParquetFile object into a Pandas dataframe:
```
Traceback (most recent call last):
  File "parquet_to_csv.py", line 47, in <module>
    df = fp_obj.to_pandas()
  File "/Users/victor.capel/anaconda2/lib/python2.7/site-packages/fastparquet/api.py", line 401, in to_pandas
    assign=parts)
  File "/Users/victor.capel/anaconda2/lib/python2.7/site-packages/fastparquet/api.py", line 202, in read_row_group_file
    assign=assign)
  File "/Users/victor.capel/anaconda2/lib/python2.7/site-packages/fastparquet/core.py", line 284, in read_row_group_file
    sep=sep)
  File "/Users/victor.capel/anaconda2/lib/python2.7/site-packages/fastparquet/core.py", line 342, in read_row_group
    val = val_to_num([p[1] for p in partitions if p[0] == cat][0])
IndexError: list index out of range
```

Do you have any idea why this is happening? Are we missing something when generating the ParquetFile object or when converting to Pandas df?

Edit: just to clarify, there are no issues when reading a single Parquet file on S3, only when loading multiple files into a same FastParquet object then attempting to convert to Pandas df.

**Comment by vcapelca** [comment]
Well, I'm gonna answer myself: it seems that the issue is in the filenames, which contain an "=" sign, so it treats the filename as a partition, messing it up. I don't know if anyone else found this issue, or if there's any way to "force" a specific partition key to be used by the ParquetFile object when converting to Pandas df.

**Comment by martindurant** [comment]
You are quite right, when supplied with a list of paths, fastparquet tries to guess where the root of the dataset is, but looking at the common path elements, and interprets the directory structure as partitioning.
You can, however, supply `root=` to `ParquetFile`, to explicitly declare which path elements to consider. This doesn't actually solve the case for you, because your files are in *different* directories - the problem actually is that some of the filenames contain `=` and some do not. This could be considered a bug in fastparquet, but it would be simple enough for you to work-around by changing the file-names.

*Comment*: you seem to have rather many files for such a small number of rows.

**Comment by martindurant** [comment]
I have looking into this, and found that there is a little lack of rigour in the partition-inference logic, which will take a little work to fix - please bear with me.

**Comment by martindurant** [comment]
The easy workaround is as follows:

    fp_obj.cats = {}

before calling `to_pandas()`. A better solution will be forthcoming.
