### ISSUE TITLE
ParquetFile error not finding _metadata directory

### ISSUE THREAD

**Issue by virtualluke** [dask/fastparquet#240]
system: centos 7.3, fastparquet 0.1.2, anaconda python 3.6.2

I created some parquet files using 

`fastparquet.write(filename,data,compression='SNAPPY') `

and now when I try to read those same files with 

`pf=ParquetFile(filename) `

I get the error: 

`NotADirectoryError: [Errno 20] Not a directory: 'filename/_metadata'`

thoughts?

**Comment by virtualluke** [comment]
just upgraded to fastparquet 0.1.3, same issue

**Comment by martindurant** [comment]
Can you please provide the complete stacktrace, and see what is actually contained within the path pointed to by `filename`?

**Comment by virtualluke** [comment]
```
# ls -al
total 16961
drwxr-xr-x 2 root root     4096 Oct 16 23:34 .
drwxr-xr-x 3 root root     4096 Oct 16 23:34 ..
-rw-r--r-- 1 root root 17359516 Oct 16 23:34 file1.parq
```
```
# python
Python 3.6.2 |Anaconda, Inc.| (default, Sep 30 2017, 18:42:57)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fastparquet
>>> fastparquet.ParquetFile('file1.parq')
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/fastparquet/api.py", line 96, in __init__
    with open_with(fn2, 'rb') as f:
  File "/opt/anaconda3/lib/python3.6/site-packages/fastparquet/util.py", line 44, in default_open
    return open(f, mode)
NotADirectoryError: [Errno 20] Not a directory: 'file1.parq/_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.6/site-packages/fastparquet/api.py", line 102, in __init__
    self._parse_header(f, verify)
  File "/opt/anaconda3/lib/python3.6/site-packages/fastparquet/api.py", line 125, in _parse_header
    self._set_attrs()
  File "/opt/anaconda3/lib/python3.6/site-packages/fastparquet/api.py", line 139, in _set_attrs
    self.schema = schema.SchemaHelper(self._schema)
  File "/opt/anaconda3/lib/python3.6/site-packages/fastparquet/schema.py", line 80, in __init__
    self.text = schema_to_text(self.schema_elements[0])
  File "/opt/anaconda3/lib/python3.6/site-packages/fastparquet/schema.py", line 47, in schema_to_text
    text += '\n' + schema_to_text(child, indent)
  File "/opt/anaconda3/lib/python3.6/site-packages/fastparquet/schema.py", line 36, in schema_to_text
    root.converted_type])
KeyError: 24
```

**Comment by martindurant** [comment]
It is the second exception that is meaningful, not the first. Apparently you have a converted_type of 24, which isn't defined. What were the dtypes of the original input data?

**Comment by martindurant** [comment]
It is the second exception that is meaningful, not the first. Apparently you have a converted_type of 24, which isn't defined. What were the dtypes of the original input data?

**Comment by virtualluke** [comment]
The file with the error came from splitting up a parquet file aka bigfile (which reads fine with fastparquet) into chunks with size < 150,000 rows as follows:

```
pf = ParquetFile(bigfile)
df = pf.to_pandas()
num_chunks = 1+ pf.count//150000
p = np.array_split(df,num_chunks)

count=1
for x in p:        
    write('file'+str(count)+'.parq',x,compression='SNAPPY')
    count+=1
```

**Comment by virtualluke** [comment]
for the file bigfile:
```
>>pf = ParquetFile(bigfile)
>>print(pf.schema)
- schema:
| - field0: BYTE_ARRAY, UTF8, OPTIONAL
| - field1: BYTE_ARRAY, UTF8, OPTIONAL
| - field2: BYTE_ARRAY, UTF8, OPTIONAL
| - field3: BYTE_ARRAY, UTF8, OPTIONAL
| - field4: INT64, OPTIONAL
| - field5: BYTE_ARRAY, JSON, OPTIONAL
| - field6: BYTE_ARRAY, JSON, OPTIONAL
| - field7: BYTE_ARRAY, UTF8, OPTIONAL
| - field8: BYTE_ARRAY, UTF8, OPTIONAL
| - field9: BYTE_ARRAY, JSON, OPTIONAL
| - field10: INT64, OPTIONAL
| - field11: BYTE_ARRAY, UTF8, OPTIONAL
| - field12: BYTE_ARRAY, UTF8, OPTIONAL
| - field13: BYTE_ARRAY, UTF8, OPTIONAL
| - field14: INT64, OPTIONAL
| - field15: INT64, OPTIONAL
| - field16: DOUBLE, OPTIONAL
| - field17: BYTE_ARRAY, UTF8, OPTIONAL
| - field18: BYTE_ARRAY, UTF8, OPTIONAL
| - field19: BYTE_ARRAY, UTF8, OPTIONAL
| - field20: BYTE_ARRAY, UTF8, OPTIONAL
| - field21: DOUBLE, OPTIONAL
| - field22: BYTE_ARRAY, UTF8, OPTIONAL
| - field23: BOOLEAN, OPTIONAL
| - field24: BOOLEAN, OPTIONAL
| - field25: BYTE_ARRAY, UTF8, OPTIONAL
| - field26: BYTE_ARRAY, UTF8, OPTIONAL
| - field27: BYTE_ARRAY, UTF8, OPTIONAL
| - field28: BYTE_ARRAY, JSON, OPTIONAL
| - field29: BYTE_ARRAY, UTF8, OPTIONAL
| - field30: BYTE_ARRAY, UTF8, OPTIONAL
| - field31: BYTE_ARRAY, UTF8, OPTIONAL
| - field32: BYTE_ARRAY, UTF8, OPTIONAL
| - field33: BYTE_ARRAY, JSON, OPTIONAL
| - field34: BYTE_ARRAY, UTF8, OPTIONAL
| - field35: BYTE_ARRAY, UTF8, OPTIONAL
| - field36: BYTE_ARRAY, JSON, OPTIONAL
| - field37: INT64, OPTIONAL
| - field38: BYTE_ARRAY, JSON, OPTIONAL
| - field39: INT64, OPTIONAL
| - field40: BYTE_ARRAY, UTF8, OPTIONAL
| - field41: BYTE_ARRAY, UTF8, OPTIONAL
| - field42: BYTE_ARRAY, UTF8, OPTIONAL
  - field43: BYTE_ARRAY, UTF8, OPTIONAL
```

**Comment by virtualluke** [comment]
```
>>>df = pf.to_pandas()
>>>df.dtypes
field0          object
field1          object
field2          object
field3          object
field4          int64
field5          object
field6          object
field7          object
field8          object
field9          object
field10         int64
field11         object
field12         object
field13         object
field14         int64
field15         int64
field16         float64
field17         object
field18         object
field19         object
field20         object
field21         float64
field22         object
field23         float16
field24         float16
field25         object
field26         object
field27         object
field28         object
field29         object
field30         object
field31         object
field32         object
field33         object
field34         object
field35         object
field36         object
field37         int64
field38         object
field39         int64
field40         object
field41         object
field42         object
field43         object
dtype: object
```

**Comment by martindurant** [comment]
by the way, you don't really need to do this: you can use the `row_group_offsets=` parameter of `write` to split up your data into chunks, which can be saved in one file or many, depending on the value of `file_scheme`.

I wonder, can you figure out which column is causing the problem? You could probably do it by dropping into debugger, or perhaps by selecting amongst your input columns and trying the process again. Are you seeing this for every partition file?

**Comment by virtualluke** [comment]
I didn't see how to use row_group_offsets with each chunked parquet file in a separate file with a simple file_scheme.

**Comment by martindurant** [comment]
Correct, you *either* have chunks in a single file with "simple" scheme, or produce multiple files, not both. When you have multiple files (like scheme "hive"), each file is independently  readable, not only as part of the whole. Chunks in a single file are probably already good enough for you, depending on how you intend to read the data.

**Comment by martindurant** [comment]
Yes, every file contains a copy of the schema, and the row-groups definition appropriate for the data in that one file. The `_metadata` file is special in that it contains links to all the other files - but it is not required.

**Comment by Wercurial** [comment]
Hello, I have the same problem, but I didn't understand your solution above. Can you elaborate? Thank you

**Comment by martindurant** [comment]
@Wercurial , the original issue here was, I think, rather specific. You are welcome to file a new issue with the specifics of your situation (what you did, what the data are like...).

**Comment by Wercurial** [comment]
> @Wercurial , the original issue here was, I think, rather specific. You are welcome to file a new issue with the specifics of your situation (what you did, what the data are like...).

Ok,thx,i will to a new issue
