### ISSUE TITLE
Filters and column's name containing dots.

### ISSUE THREAD

**Issue by Thomas-Z** [dask/fastparquet#245]
I'm dealing with data using column's names with dots and almost everything seems to work with these names except the filters option.

```python
data = np.random.randint(1, high=100, size=8)
df = pd.DataFrame({'col.n1': data})
fp.write(file_name, df, compression='SNAPPY')

pq_file = fp.ParquetFile(file_name)
df = pq_file.to_pandas(filters=[('col.n1', '>', 10)])
Traceback (most recent call last):
  File "/home/xxxx/.virtualenvs/parquet/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-94-168b372b1b53>", line 1, in <module>
    table_frame = pq_file.to_pandas(filters=[('col.n1', '>', 10)])
  File "/home/xxxx/.virtualenvs/parquet/local/lib/python2.7/site-packages/fastparquet/api.py", line 381, in to_pandas
    rgs = self.filter_row_groups(filters)
  File "/home/xxxx/.virtualenvs/parquet/local/lib/python2.7/site-packages/fastparquet/api.py", line 276, in filter_row_groups
    not(filter_out_stats(rg, filters, self.schema)) and
  File "/home/xxxx/.virtualenvs/parquet/local/lib/python2.7/site-packages/fastparquet/api.py", line 539, in filter_out_stats
    se = schema.schema_element(name)
  File "/home/xxxx/.virtualenvs/parquet/local/lib/python2.7/site-packages/fastparquet/schema.py", line 96, in schema_element
    root = root.children[part]
KeyError: u'col'

```

It's still possible to do this
```python
df = pq_file.to_pandas()
df = df[df['col.n1'] > 10]
```
But we might read some additional data.

I guess this behavior is a side effect of the way nested schema are handled but I'm not sure if this is wanted or not.

Thanks and regards,
Thomas

**Comment by martindurant** [comment]
Yes, I believe you are right, the dotted column name is being decomposed, and the code is looking for nested columns. `schema.schema_element` should presumably have a direct check for a column of that name before trying nested structures. Would you be willing to make this fix and add a test?

**Comment by Thomas-Z** [comment]
I won't have time to really look into this in the coming weeks but, if my python skills are good enough, I'll definitely try to fix it as soon as I have some time.
