### ISSUE TITLE
Set pandas version in requirements.txt

### ISSUE THREAD

**Issue by bwo** [dask/fastparquet#269]
```
$ python -c 'import fastparquet'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
[...]
  File "/home/ben/.virtualenvs/dev/local/lib/python2.7/site-packages/fastparquet/dataframe.py", line 6, in <module>
    from pandas.core.index import RangeIndex, Index
ImportError: cannot import name RangeIndex
```

**Comment by martindurant** [comment]
@TomAugspurger , what do you recommend as the minimum pandas requirement?

**Comment by TomAugspurger** [comment]
0.21.0 would get you `CategoricalDtype`, but that's pretty recent (October 2017).

Otherwise, maybe 0.19 (Octoboer 2016).
