### ISSUE TITLE
manylinux wheel on pypi?

### ISSUE THREAD

**Issue by erikcw** [dask/fastparquet#319]
I'm working on porting a project that uses fastparquet over to AWS Lambda (using [Zappa](https://github.com/Miserlou/Zappa)).

It's quite difficult to deploy fastparquet in this situation because of the cython compilation step which AWS doesn't support out of the box.  Seems like the community is converging on "[manylinux](https://github.com/pypa/manylinux)" wheels for this type of scenario which work quite well.

I see that there is already a Windows wheel available on pypi -- would it be possible to include manylinux wheels in the release process?

```
[1521750090013] No module named 'fastparquet.speedups': ModuleNotFoundError
Traceback (most recent call last):
  File "/var/task/handler.py", line 509, in lambda_handler
  return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 240, in lambda_handler
  return handler.handler(event, context)
  File "/var/task/handler.py", line 386, in handler
  app_function = self.import_module_and_get_function(whole_function)
  File "/var/task/handler.py", line 231, in import_module_and_get_function
  app_module = importlib.import_module(module)
  File "/var/lang/lib/python3.6/importlib/__init__.py", line 126, in import_module
  return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/tmp/convert-to-parq/app.py", line 25, in <module>
  from parquet import write_to_parquet
  File "/tmp/convert-to-parq/parquet.py", line 1, in <module>
  import fastparquet
  File "/tmp/convert-to-parq/fastparquet/__init__.py", line 8, in <module>
  from .core import read_thrift
  File "/tmp/convert-to-parq/fastparquet/core.py", line 13, in <module>
  from . import encoding
  File "/tmp/convert-to-parq/fastparquet/encoding.py", line 11, in <module>
  from .speedups import unpack_byte_array
ModuleNotFoundError: No module named 'fastparquet.speedups'
```

**Comment by martindurant** [comment]
I would be happy to see that happen, but I'm afraid I don't know how to bring it about.

**Comment by martindurant** [comment]
Note that the source install now includes the .c code from cython, which may help you (but you still need a compilation step if using that).

**Comment by jleclanche** [comment]
@martindurant Here's a good example on how to do it using travis (but you can do it locally as well if you prefer):

https://github.com/pypa/python-manylinux-demo

**Comment by simonvanderveldt** [comment]
@martindurant Why has this issue been closed?
The 0.2.0 release on pypi doesn't contain any wheels so it doesn't seem fixed.

**Comment by martindurant** [comment]
"won't fix" - unless someone helps me to achieve it.
