### ISSUE TITLE
fastparquet fails to parse parquet files with column containing a number list

### ISSUE THREAD

**Issue by marcusklaas** [dask/fastparquet#323]
Fastparquet seems to have trouble parsing parquet files into a pandas Dataframe when the parquet files have the following schema:
```
- spark_schema:
| - _1: INT32, REQUIRED
  - _2: LIST, OPTIONAL
    - list: REPEATED
      - element: DOUBLE, REQUIRED
```
It results in the following stacktrace on my machine:
```
Traceback (most recent call last):
  File "app.py", line 55, in <module>
    pf = print(ParquetFile(['spark-model/1.snappy.parquet', 'spark-model/2.snappy.parquet', 'spark-model/3.snappy.parquet']).to_pandas(index=False))
  File "/home/marcus/anaconda3/lib/python3.6/site-packages/fastparquet/api.py", line 405, in to_pandas
    assign=parts)
  File "/home/marcus/anaconda3/lib/python3.6/site-packages/fastparquet/api.py", line 205, in read_row_group_file
    assign=assign, scheme=self.file_scheme)
  File "/home/marcus/anaconda3/lib/python3.6/site-packages/fastparquet/core.py", line 284, in read_row_group_file
    scheme=scheme)
  File "/home/marcus/anaconda3/lib/python3.6/site-packages/fastparquet/core.py", line 334, in read_row_group
    cats, selfmade, assign=assign)
  File "/home/marcus/anaconda3/lib/python3.6/site-packages/fastparquet/core.py", line 311, in read_row_group_arrays
    catdef=out[name+'-catdef'] if use else None)
  File "/home/marcus/anaconda3/lib/python3.6/site-packages/fastparquet/core.py", line 235, in read_col
    skip_nulls, selfmade=selfmade)
  File "/home/marcus/anaconda3/lib/python3.6/site-packages/fastparquet/core.py", line 103, in read_data_page
    repetition_levels = read_rep(io_obj, daph, helper, metadata)
  File "/home/marcus/anaconda3/lib/python3.6/site-packages/fastparquet/core.py", line 85, in read_rep
    bit_width)[:daph.num_values]
  File "/home/marcus/anaconda3/lib/python3.6/site-packages/fastparquet/core.py", line 46, in read_data
    raise NotImplementedError('Encoding %s' % coding)
NotImplementedError: Encoding 4
```

**Comment by martindurant** [comment]
Encoding 4 would be bitpacking, which should not be used https://github.com/apache/parquet-format/blob/master/Encodings.md#bit-packed-deprecated-bit_packed--4 . Is your data ancient? The encoding could be implemented, but there is not much call for it. Alternatively, if is possible that your file is corrupted somehow.

**Comment by marcusklaas** [comment]
Oooh, that's interesting. I generated it using a fairly recent version of Spark (2.2.1). If the encoding is deprecated, then the solution should definitely be sought in the file creation instead of parsing. I'll close this issue.

Thanks for your insightful and super quick response. You helped me out a bunch already!
