### ISSUE TITLE
IndexError when loading zero-column DataFrame

### ISSUE THREAD

**Issue by adamhooper** [dask/fastparquet#361]
fastparquet can save a zero-column DataFrame, but it can't load it. Here's the test case:

```
>>> import fastparquet
>>> import pandas
>>> fastparquet.write('empty.parq', pandas.DataFrame({'A': ['a', 'b',' c']})[[]])
>>> fastparquet.ParquetFile('empty.parq')
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/fastparquet/api.py", line 110, in __init__
    with open_with(fn2, 'rb') as f:
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/fastparquet/util.py", line 38, in default_open
    return open(f, mode)
NotADirectoryError: [Errno 20] Not a directory: 'empty.parq/_metadata'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/fastparquet/api.py", line 116, in __init__
    self._parse_header(f, verify)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/fastparquet/api.py", line 140, in _parse_header
    self._set_attrs()
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/fastparquet/api.py", line 157, in _set_attrs
    for rg in self.row_groups])
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/fastparquet/api.py", line 157, in <listcomp>
    for rg in self.row_groups])
IndexError: list index out of range
```

**Comment by adamhooper** [comment]
Okay, I'll give it a shot :)
