### ISSUE TITLE
Please include instructions to get test passing for Windows

### ISSUE THREAD

**Issue by klahnakoski** [dask/fastparquet#393]
A naive install of Conda, on Windows, and attempting to run tests, does not work. Installing fastparquet on regular Python does not work on Windows either.

Please update the docs to include all steps required to get the test suite passing.

```
C:\Users\kyle\code\fastparquet>C:\Users\kyle\Anaconda3\python.exe -m pytest fastparquet\test
Traceback (most recent call last):
  File "C:\Users\kyle\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kyle\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\kyle\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kyle\Anaconda3\lib\site-packages\pytest.py", line 91, in <module>
    raise SystemExit(pytest.main())
  File "C:\Users\kyle\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 58, in main
    config = _prepareconfig(args, plugins)
  File "C:\Users\kyle\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 196, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "C:\Users\kyle\Anaconda3\lib\site-packages\pluggy\hooks.py", line 284, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "C:\Users\kyle\Anaconda3\lib\site-packages\pluggy\manager.py", line 67, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "C:\Users\kyle\Anaconda3\lib\site-packages\pluggy\manager.py", line 61, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "C:\Users\kyle\Anaconda3\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "C:\Users\kyle\Anaconda3\lib\site-packages\_pytest\helpconfig.py", line 93, in pytest_cmdline_parse
    config = outcome.get_result()
  File "C:\Users\kyle\Anaconda3\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\kyle\Anaconda3\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\kyle\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 675, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Users\kyle\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 854, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Users\kyle\Anaconda3\lib\site-packages\_pytest\config\__init__.py", line 808, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "C:\Users\kyle\Anaconda3\lib\site-packages\pluggy\manager.py", line 267, in load_setuptools_entrypoints
    plugin = ep.load()
  File "C:\Users\kyle\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "C:\Users\kyle\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\kyle\Anaconda3\lib\site-packages\_pytest\assertion\rewrite.py", line 295, in load_module
    six.exec_(co, mod.__dict__)
  File "C:\Users\kyle\Anaconda3\lib\site-packages\pytest_doctestplus\plugin.py", line 17, in <module>
    from .output_checker import OutputChecker, FIX
  File "C:\Users\kyle\Anaconda3\lib\site-packages\_pytest\assertion\rewrite.py", line 295, in load_module
    six.exec_(co, mod.__dict__)
  File "C:\Users\kyle\Anaconda3\lib\site-packages\pytest_doctestplus\output_checker.py", line 10, in <module>
    import numpy as np
  File "C:\Users\kyle\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\kyle\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\kyle\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\kyle\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\kyle\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.
```

**Comment by martindurant** [comment]
@klahnakoski , happy to help however I can. You may have noticed, though, that fastparquet has been in bugfix mode, rather than new development, for a while. 

Note the interesting side-discussion in https://github.com/scikit-hep/awkward-array/issues/65

For the build, it looks at though numpy isn't importing, not fastparquet. Can you confirm that numpy loads as expected? There is a pytest-numpy that may be getting in the way and numpy has had a new release recently, so I suspect the exact version numbers will matter here.
