### ISSUE TITLE
List index out of range on some nested Parquet files

### ISSUE THREAD

**Issue by cmenguy** [dask/fastparquet#426]
This seems like the same error as #352 
My Parquet file is nested with only simple types.
This error does not happen on all nested Parquet files, just this particular one.

However, I also want to point out that I am able to read this file correctly with fastparquet 0.1.4 (it returns a dict instead of individual columns which is still not ideal but at least workable, as opposed to currently having it just error out), but it started breaking after that. This issue was closed as not supported, but it appears it was supported in earlier versions, so I am not sure if that makes sense.

Also same file can be read fine in pyarrow, so I think something is up. I am looking at the code now to see if I can fix it, but in the meantime if you have any ideas let me know.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parquet.py", line 288, in read_parquet
    return impl.read(path, columns=columns, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pandas/io/parquet.py", line 232, in read
    parquet_file = self.api.ParquetFile(path)
  File "/usr/local/lib/python2.7/site-packages/fastparquet/api.py", line 116, in __init__
    self._parse_header(f, verify)
  File "/usr/local/lib/python2.7/site-packages/fastparquet/api.py", line 140, in _parse_header
    self._set_attrs()
  File "/usr/local/lib/python2.7/site-packages/fastparquet/api.py", line 157, in _set_attrs
    self._dtypes()
  File "/usr/local/lib/python2.7/site-packages/fastparquet/api.py", line 505, in _dtypes
    chunk = rg.columns[i]
IndexError: list index out of range
```

[tempFile.parquet.zip](https://github.com/dask/fastparquet/files/3143366/tempFile.parquet.zip)

**Comment by cmenguy** [comment]
[tempFile.parquet.zip](https://github.com/dask/fastparquet/files/3143365/tempFile.parquet.zip)

**Comment by martindurant** [comment]
Can you run a bisect to find out which specific commit broke?

**Comment by cmenguy** [comment]
@martindurant The commit that broke it is https://github.com/dask/fastparquet/commit/2df5214369b5ba9920c272d6c9d43fa70426d8ac

And I think I understand why: `dtype` has 6 columns, while `rg.columns` has 5. It's because, since it's nested, the nested structure itself appears as a column in `dtype` but not `rg.columns`. Which is strange because for most files I've tried, even nested, it doesn't have a problem.

**Comment by martindurant** [comment]
Can you check for the working/not working cases whether they have the same optional/nullability of the columns?

**Comment by cmenguy** [comment]
@martindurant A Parquet file that doesn't work since this commit: 

```
file:             file:/Users/cmenguy/Downloads/tempFile.parquet
creator:          parquet-mr version 1.10.0 (build 031a6654009e3b82020012a18434c582bd74c73a)
extra:            org.apache.spark.sql.parquet.row.metadata = {"type":"struct","fields":[{"name":"_adobe_corpnew","type":{"type":"struct","fields":[{"name":"id","type":"integer","nullable":true,"metadata":{}},{"name":"vocab","type":"string","nullable":true,"metadata":{}},{"name":"frequency","type":"integer","nullable":true,"metadata":{}},{"name":"max_len","type":"double","nullable":true,"metadata":{}},{"name":"reduced_max_len","type":"integer","nullable":true,"metadata":{}}]},"nullable":false,"metadata":{}}]}

file schema:      spark_schema
--------------------------------------------------------------------------------
_adobe_corpnew:   REQUIRED F:5
.id:              OPTIONAL INT32 R:0 D:1
.vocab:           OPTIONAL BINARY O:UTF8 R:0 D:1
.frequency:       OPTIONAL INT32 R:0 D:1
.max_len:         OPTIONAL DOUBLE R:0 D:1
.reduced_max_len: OPTIONAL INT32 R:0 D:1

row group 1:      RC:100 TS:2463 OFFSET:4
--------------------------------------------------------------------------------
_adobe_corpnew:
.id:               INT32 SNAPPY DO:0 FPO:4 SZ:460/455/0.99 VC:100 ENC:PLAIN,BIT_PACKED,RLE
.vocab:            BINARY SNAPPY DO:0 FPO:464 SZ:918/1394/1.52 VC:100 ENC:PLAIN,BIT_PACKED,RLE
.frequency:        INT32 SNAPPY DO:0 FPO:1382 SZ:456/448/0.98 VC:100 ENC:BIT_PACKED,PLAIN_DICTIONARY,RLE
.max_len:          DOUBLE SNAPPY DO:0 FPO:1838 SZ:97/93/0.96 VC:100 ENC:BIT_PACKED,PLAIN_DICTIONARY,RLE
.reduced_max_len:  INT32 SNAPPY DO:0 FPO:1935 SZ:77/73/0.95 VC:100 ENC:BIT_PACKED,PLAIN_DICTIONARY,RLE
```

Another one similarly nested that works:
```
file:                     file:/Users/cmenguy/Downloads/tempFile-verygood.parquet
creator:                  parquet-mr version 1.8.2 (build c6522788629e590a53eb79874b95f6c3ff11f16c)
extra:                    org.apache.spark.sql.parquet.row.metadata = {"type":"struct","fields":[{"name":"_adobe_corpnew","type":{"type":"struct","fields":[{"name":"complete_list","type":"string","nullable":true,"metadata":{}},{"name":"current_realized_traits","type":"string","nullable":true,"metadata":{}},{"name":"e0","type":"string","nullable":true,"metadata":{}},{"name":"e1","type":"string","nullable":true,"metadata":{}},{"name":"e2","type":"string","nullable":true,"metadata":{}},{"name":"e3","type":"string","nullable":true,"metadata":{}},{"name":"history","type":"string","nullable":true,"metadata":{}}]},"nullable":false,"metadata":{}},{"name":"_id","type":"string","nullable":true,"metadata":{}}]}

file schema:              spark_schema
--------------------------------------------------------------------------------
_adobe_corpnew:           REQUIRED F:7
.complete_list:           OPTIONAL BINARY O:UTF8 R:0 D:1
.current_realized_traits: OPTIONAL BINARY O:UTF8 R:0 D:1
.e0:                      OPTIONAL BINARY O:UTF8 R:0 D:1
.e1:                      OPTIONAL BINARY O:UTF8 R:0 D:1
.e2:                      OPTIONAL BINARY O:UTF8 R:0 D:1
.e3:                      OPTIONAL BINARY O:UTF8 R:0 D:1
.history:                 OPTIONAL BINARY O:UTF8 R:0 D:1
_id:                      OPTIONAL BINARY O:UTF8 R:0 D:1

row group 1:              RC:112744 TS:115867545 OFFSET:4
--------------------------------------------------------------------------------
_adobe_corpnew:
.complete_list:            BINARY SNAPPY DO:0 FPO:4 SZ:5882900/18976795/3.23 VC:112744 ENC:BIT_PACKED,RLE,PLAIN,PLAIN_DICTIONARY
.current_realized_traits:  BINARY SNAPPY DO:0 FPO:5882904 SZ:5941756/18989194/3.20 VC:112744 ENC:BIT_PACKED,RLE,PLAIN,PLAIN_DICTIONARY
.e0:                       BINARY SNAPPY DO:0 FPO:11824660 SZ:643987/862233/1.34 VC:112744 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY
.e1:                       BINARY SNAPPY DO:0 FPO:12468647 SZ:653075/894277/1.37 VC:112744 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY
.e2:                       BINARY SNAPPY DO:0 FPO:13121722 SZ:648367/863398/1.33 VC:112744 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY
.e3:                       BINARY SNAPPY DO:0 FPO:13770089 SZ:647141/862093/1.33 VC:112744 ENC:BIT_PACKED,RLE,PLAIN_DICTIONARY
.history:                  BINARY SNAPPY DO:0 FPO:14417230 SZ:10751478/69683728/6.48 VC:112744 ENC:BIT_PACKED,RLE,PLAIN,PLAIN_DICTIONARY
_id:                       BINARY SNAPPY DO:0 FPO:25168708 SZ:3760661/4735827/1.26 VC:112744 ENC:BIT_PACKED,RLE,PLAIN
```

I think I understand why one is working and not the other: the one that's not working only has a nested structure and nothing outside of it. But the ones I have that are working have nested structure + some other columns outside of it. So probably when inferring the types even the ones that don't crash are still slightly wrong (but in output it mostly looks fine).
