### ISSUE TITLE
ValueError ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216

### ISSUE THREAD

**Issue by TomAugspurger** [dask/fastparquet#444]
I think there's an issue with the Conda-forge package for NumPy 1.15.x

```
conda create -n tst -c conda-forge --force python=3.6.7 fastparquet numpy=1.15.4 
```

```
bash-5.0$ python -c "import fastparquet"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/taugspurger/miniconda3/envs/tst/lib/python3.6/site-packages/fastparquet/__init__.py", line 8, in <module>
    from .core import read_thrift
  File "/Users/taugspurger/miniconda3/envs/tst/lib/python3.6/site-packages/fastparquet/core.py", line 9, in <module>
    from . import encoding
  File "/Users/taugspurger/miniconda3/envs/tst/lib/python3.6/site-packages/fastparquet/encoding.py", line 11, in <module>
    from .speedups import unpack_byte_array
  File "__init__.pxd", line 872, in init fastparquet.speedups
ValueError: numpy.ufunc has the wrong size, try recompiling. Expected 192, got 216
```

I haven't diagnosed the issue yet. Using NumPy 1.16 is fine.

**Comment by martindurant** [comment]
Better ask a conda-forge person here, it's possible that the cython compilation needs additional steps compared to when the recipe was last changed.

**Comment by TomAugspurger** [comment]
Can you explain how fasparquet uses Cython? It looks like the compiled `.c` files are committed to the repo?

**Comment by TomAugspurger** [comment]
If that's the case, then they should likely be compiled with the oldest supported NumPy & cython.

**Comment by martindurant** [comment]
The `.c` files are included to aid pip compilation. They should be remade by cython at conda build time for the given environment.

**Comment by jrbourbeau** [comment]
FWIW https://github.com/conda-forge/fastparquet-feedstock/pull/27#issuecomment-514346076 mentions that this issue should be fixed, however I seemed to have stumbled across this `ValueError` with the latest `fastparquet` release on conda-forge (0.5.0) (xref https://github.com/dask/dask/pull/7006/checks?check_run_id=2035433841#step:7:16667)

**Comment by martindurant** [comment]
@jrbourbeau , can you ping on that issue, maybe Marius can help. I don't understand enough about the build process - maybe it will need more careful numpy version pinning?
