### ISSUE TITLE
Pip installing fastparquet on Linux requests a pre-release version of numpy

### ISSUE THREAD

**Issue by tswast** [dask/fastparquet#445]
We're getting failure to install `fastparquet` on Python 2.7 due to a dependency on a pre-release version of numpy. https://github.com/googleapis/google-cloud-python/issues/8549

This is reproducible by running `pip install fastparquet` on a Python 2.7 virtualenv.

```
$ pip install fastparquet
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintain[40/550]
 that date. A future version of pip will drop support for Python 2.7.
Collecting fastparquet
  Using cached https://files.pythonhosted.org/packages/85/b9/dc59386bc5824f86c640e7178fc78986f0c81763b924b2e37337ffb6a563/fastparquet-0.3.1.tar
.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-QzepJr/fastparquet/setup.py", line 98, in <module>
        **extra
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/__init__.py", line 139, in _install_setup_require
s
        dist.fetch_build_eggs(dist.setup_requires)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 866, in resolve
        replace_conflicting=replace_conflicting
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1146, in best_match
        return self.obtain(req, installer)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1158, in obtain
        return installer(requirement)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 679, in easy_insta
ll
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 705, in install_it
em
        dists = self.install_eggs(spec, download, tmpdir)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 890, in install_eg
gs
        return self.build_and_install(setup_script, setup_base)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1158, in build_and
_install
        self.run_setup(setup_script, setup_base, args)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
        self.gen.throw(type, value, traceback)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/usr/local/google/home/swast/venv/bq/local/lib/python2.7/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-jVnDVe/numpy-1.17.0rc1/setup.py", line 31, in <module>
        modules_to_build = {
    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-QzepJr/fastparquet/
```

This also affects Python 3, in that a pre-release version of numpy is still installed.

**Comment by martindurant** [comment]
fastpaquet does not specify to use such a new numpy at all, so I have no idea why it's being selected - perhaps pandas or numba? You should always be able to install specific versions of things listed in requirements which are ok on your system.
fastparquet requirements:
```
pandas>=0.19
numba>=0.28
numpy>=1.11
thrift>=0.11.0
six
```
(note that a py3-only version may indeed be coming, because it improves string performance by 50%)

**Comment by tswast** [comment]
The wheels shouldn't specify numpy, but `setup.py` definitely does.

**Comment by martindurant** [comment]
Sorry, it's been a while since I've looked at the build stuff, where is the prerelease version being picked up? I see only https://github.com/dask/fastparquet/blob/master/requirements.txt#L3

**Comment by tswast** [comment]
I'm not able to reproduce today. Very strange. Maybe numpy had a prerelease package that wasn't actually marked correctly, but I'm not seeing any recent changes on PyPI or issues on GitHub.

**Comment by asolimando** [comment]
It's still broken for me with python 2.7 on both Mac and Linux (very same error), any suggestions?

**Comment by martindurant** [comment]
I did not think that numpy was releasing for py27 at all any more, perhaps that's the problem. You should manually choose a version that works for you, get the dependencies for fastparquet too, then pip-install fastparquet with `--no-deps`. You would be best off getting cython too and re-making the C code.
