### ISSUE TITLE
Latest version of fastparquet/s3fs/fsspec incompatible with dask/distributed 2.1.0.

### ISSUE THREAD

**Issue by birdsarah** [dask/fastparquet#460]
Latest version of fastparquet/s3fs/fsspec incompatible with dask/distributed 2.1.0.

When running dask/distributed pinned to 2.1.0 with latest version of s3fs and fastparquet 
installed from conda-forge to give the env detailed: https://gist.github.com/birdsarah/a1eebbe5e5320f3e613cfc7277afe0a2

I get the following error when trying to write_parquet

```
08/29/2019 03:23:08 AM UTC expected list of bytes
Traceback (most recent call last):
  File "<ipython-input-12-b0b8e2c0fe2e>", line 15, in <module>
    storage_options={'s3_additional_kwargs': sse_args},
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/dask/dataframe/core.py", line 3618, in to_parquet
    return to_parquet(self, path, *args, **kwargs)
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/dask/dataframe/io/parquet.py", line 1496, in to_parquet
    out.compute()
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/dask/base.py", line 175, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/dask/base.py", line 446, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/distributed/client.py", line 2527, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/distributed/client.py", line 1823, in gather
    asynchronous=asynchronous,
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/distributed/client.py", line 763, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/distributed/utils.py", line 332, in sync
    six.reraise(*error[0])
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/six.py", line 693, in reraise
    raise value
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/distributed/utils.py", line 317, in f
    result[0] = yield future
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/distributed/client.py", line 1680, in _gather
    six.reraise(type(exception), exception, traceback)
  File "/mnt/miniconda/envs/jestr-etl/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/mnt/yarn/usercache/hadoop/appcache/application_1566335097751_3811/container_1566335097751_3811_01_000029/environment/lib/python3.7/site-packages/dask/dataframe/io/parquet.py", line 668, in _write_partition_fastparquet
  File "/mnt/yarn/usercache/hadoop/appcache/application_1566335097751_3811/container_1566335097751_3811_01_000029/environment/lib/python3.7/site-packages/fastparquet/writer.py", line 631, in make_part_file
  File "/mnt/yarn/usercache/hadoop/appcache/application_1566335097751_3811/container_1566335097751_3811_01_000029/environment/lib/python3.7/site-packages/fastparquet/writer.py", line 619, in make_row_group
  File "/mnt/yarn/usercache/hadoop/appcache/application_1566335097751_3811/container_1566335097751_3811_01_000029/environment/lib/python3.7/site-packages/fastparquet/writer.py", line 513, in write_column
  File "/mnt/yarn/usercache/hadoop/appcache/application_1566335097751_3811/container_1566335097751_3811_01_000029/environment/lib/python3.7/site-packages/fastparquet/writer.py", line 254, in encode_plain
  File "fastparquet/speedups.pyx", line 112, in fastparquet.speedups.pack_byte_array
    raise TypeError("expected list of bytes")
TypeError: expected list of bytes
```

**Comment by birdsarah** [comment]
I thought it was maybe the brand new release of python-snappy (0.5.4) but that didn't change anything.

**Comment by birdsarah** [comment]
....i'm starting to wonder if this is my data.

**Comment by birdsarah** [comment]
....latest update is that if I take a smaller part of my data that I can fit in memory I can get it out as a pandas dataframe and write it to local disk. But when I try and write that same data from the dask dataframe it fails. This is probably not a fastparquet issue.

**Comment by birdsarah** [comment]
Apologies for the noise. No version compatibility issues.
