### ISSUE TITLE
KeyError: 0 - Works in Pandas, not in Dask

### ISSUE THREAD

**Issue by oeyvindds** [dask/fastparquet#467]
This is the exact input. It works fine in Pandas, but not in Dask:

from fastparquet import write
df = dsk.compute()

df.to_parquet('data/yelp_subset.parq', compression='gzip')

write('data/yelp_subset.parq',dsk, compression='gzip')

Traceback (most recent call last):
  File "/Users/oeyvind/.local/share/virtualenvs/dds-qlJdqjIA/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2897, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/oeyvind/.local/share/virtualenvs/dds-qlJdqjIA/lib/python3.7/site-packages/fastparquet/writer.py", line 849, in write
    cols = set(data)
  File "/Users/oeyvind/.local/share/virtualenvs/dds-qlJdqjIA/lib/python3.7/site-packages/dask/dataframe/core.py", line 3234, in __getitem__
    meta = self._meta[_extract_meta(key)]
  File "/Users/oeyvind/.local/share/virtualenvs/dds-qlJdqjIA/lib/python3.7/site-packages/pandas/core/frame.py", line 2995, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/Users/oeyvind/.local/share/virtualenvs/dds-qlJdqjIA/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2899, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 107, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 131, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1607, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1614, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

Does anyone have any idea about what have gone wrong here? The file is about 70 mb.

**Comment by martindurant** [comment]
You should use the dask `to_parquet` method of a dataframe, not fastparquet's `write` function, which was specifically made for pandas dataframe. Other than that, the exception does not mean much to me.

**Comment by oeyvindds** [comment]
Thanks. That did actually fix it. My bad :-(
