### ISSUE TITLE
Release wheels for Python 3.8

### ISSUE THREAD

**Issue by tswast** [dask/fastparquet#468]
When trying to install `fastparquet` in Python 3.8, I get the following error:

```
$ pip install fastparquet
Processing /Users/swast/Library/Caches/pip/wheels/b9/36/13/01416a760ddcab0eb8281ec9c9ffcbed945c9b831647c8b904/fastparquet-0.3.2-cp38-cp38-macosx_10_9_x86_64.whl
Processing /Users/swast/Library/Caches/pip/wheels/f7/e4/ac/860af9e439e40f5beccba61955fdaa04ee329e79f33d644d5c/numba-0.46.0-cp38-cp38-macosx_10_9_x86_64.whl
Requirement already satisfied: six in ./.nox/unit-3-8/lib/python3.8/site-packages (from fastparquet) (1.13.0)
Requirement already satisfied: pandas>=0.19 in ./.nox/unit-3-8/lib/python3.8/site-packages (from fastparquet) (0.25.3)
Processing /Users/swast/Library/Caches/pip/wheels/02/a2/46/689ccfcf40155c23edc7cdbd9de488611c8fdf49ff34b1706e/thrift-0.13.0-cp38-cp38-macosx_10_9_x86_64.whl
Requirement already satisfied: numpy>=1.11 in ./.nox/unit-3-8/lib/python3.8/site-packages (from fastparquet) (1.17.4)
Collecting llvmlite>=0.30.0dev0
  Using cached https://files.pythonhosted.org/packages/8b/b0/df26861e6ce2fc91c8bb93ea808fa2e631ee8a29fc4c3bc96626b78dae74/llvmlite-0.30.0.tar.gz
Requirement already satisfied: pytz>=2017.2 in ./.nox/unit-3-8/lib/python3.8/site-packages (from pandas>=0.19->fastparquet) (2019.3)
Requirement already satisfied: python-dateutil>=2.6.1 in ./.nox/unit-3-8/lib/python3.8/site-packages (from pandas>=0.19->fastparquet) (2.8.1)
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/swast/src/google-cloud-python/bigquery/.nox/unit-3-8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-wheel-61sg6l15 --python-tag cp38
       cwd: /private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/
  Complete output (26 lines):
  running bdist_wheel
  /Users/swast/src/google-cloud-python/bigquery/.nox/unit-3-8/bin/python3.8 /private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/ffi/build.py", line 168, in <module>
      main()
    File "/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/ffi/build.py", line 162, in main
      main_posix('osx', '.dylib')
    File "/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/ffi/build.py", line 107, in main_posix
      raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/Users/swast/src/google-cloud-python/bigquery/.nox/unit-3-8/bin/python3.8' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, numba, thrift, fastparquet
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/swast/src/google-cloud-python/bigquery/.nox/unit-3-8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-record-pgd56hvj/install-record.txt --single-version-externally-managed --compile --install-headers /Users/swast/src/google-cloud-python/bigquery/.nox/unit-3-8/bin/../include/site/python3.8/llvmlite
         cwd: /private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/llvmlite/_version.py {'version': '0.30.0', 'full': '3cad106e2f727bc400f1b426ce306b1e30e34b72'}
    running build_ext
    /Users/swast/src/google-cloud-python/bigquery/.nox/unit-3-8/bin/python3.8 /private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/ffi/build.py", line 168, in <module>
        main()
      File "/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/ffi/build.py", line 162, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/Users/swast/src/google-cloud-python/bigquery/.nox/unit-3-8/bin/python3.8' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/swast/src/google-cloud-python/bigquery/.nox/unit-3-8/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/setup.py'"'"'; __file__='"'"'/private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-install-yjstph0o/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/sm/phwfkhts38114zggj4_l13pc006gf0/T/pip-record-pgd56hvj/install-record.txt --single-version-externally-managed --compile --install-headers /Users/swast/src/google-cloud-python/bigquery/.nox/unit-3-8/bin/../include/site/python3.8/llvmlite Check the logs for full command output.
```

**Comment by martindurant** [comment]
I suppose LLVM/numba are not yet completely ready for py38. Recommend using 37...
