### ISSUE TITLE
fastparquet 0.3.2 RuntimeError: Ran out of input

### ISSUE THREAD

**Issue by apiszcz** [dask/fastparquet#473]
Any thoughts or advice on the following stack trace appreciated.
This occurs after hours of and hundreds of reads.

```
Traceback (most recent call last):
  File "lib\_testp\testp.py", line 1626, in <module>
    main()
  File "lib\_testp\testp.py", line 1616, in main
    ost.run(oc, ol, ou, modes, src)
  File "lib\_testp\testp.py", line 1398, in run
    self.track(oc, ol, ou, modes, src)
  File "lib\_testp\testp.py", line 724, in track
    df,t_pf = get_parquet_filtered()
  File "lib\_testp\testp.py", line 850, in track_get_parquet_filtered
    ('data', '<=', 100),
  File "C:\user1\lib\fastparquet\api.py", line 430, in to_pandas
    index=index, assign=parts)
  File "C:\user1\lib\fastparquet\api.py", line 259, in read_row_group
    scheme=self.file_scheme)
  File "C:\user1\lib\fastparquet\core.py", line 354, in read_row_group
    cats, selfmade, assign=assign)
  File "C:\user1\lib\fastparquet\core.py", line 331, in read_row_group_arrays
    catdef=out.get(name+'-catdef', None))
  File "C:\user1\lib\fastparquet\core.py", line 245, in read_col
    skip_nulls, selfmade=selfmade)
  File "C:\user1\lib\fastparquet\core.py", line 118, in read_data_page
    width=width)
  File "C:\user1\lib\fastparquet\encoding.py", line 56, in read_plain
    return np.array(unpack_byte_array(raw_bytes, count), dtype='O')
  File "fastparquet\speedups.pyx", line 163, in fastparquet.speedups.unpack_byte_array
RuntimeError: Ran out of input

```

**Comment by quasiben** [comment]
Two questions come to mind:
1) Could the file be empty ?
2) How was the file generate ?

**Comment by apiszcz** [comment]
1. yes, that is possible, will check for that.
2. create from a pandas data frame.
            fastparquet.write(opath,
                              df,
                              append=True,
                              has_nulls=True)
