### ISSUE TITLE
Index KeyError when appending

### ISSUE THREAD

**Issue by gvelchuru** [dask/fastparquet#478]
I get the following error when appending a DataFrame (after checking all columns, etc. are the same)

```
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    HOLDINGS = ta.get_data()
  File "/home/ubuntu/theta_gang/daily_price/price_module.py", line 196, in get_data
    compute=True,
  File "/home/ubuntu/miniconda3/envs/dev/lib/python3.7/site-packages/dask/dataframe/core.py", line 3751, in to_parquet
    return to_parquet(self, path, *args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/dev/lib/python3.7/site-packages/dask/dataframe/io/parquet/core.py", line 424, in to_parquet
holdings queue worker exited
    **kwargs_pass
  File "/home/ubuntu/miniconda3/envs/dev/lib/python3.7/site-packages/dask/dataframe/io/parquet/fastparquet.py", line 432, in initialize_write
    old_end = minmax[index_cols[0]]["max"][-1]
KeyError: 'index'
```

The offending line is here:
```      
self.dask_frame.to_parquet(
              "s3://tmp-th" if self.dry_run else self.datapath,
              append=not self.dry_run,
              compute=True,
          )
```
Any idea why this is?

**Comment by martindurant** [comment]
This should be posted to dask, since you are working with a dask dataframe. 
@rjzamora might be interested in following up.

**Comment by rjzamora** [comment]
Agree with @martindurant - Please do open an issue in dask (if possible, including a simple reproducer that I can run locally).

With that said, it looks like you are trying to append to a dataset that does **not** include a column called `"index"` (the default name of an index that is converted to a column).  This probably means that you don't actually want to include the index of your dask.dataframe object when you write/append to the dataset (since it is not included as a column in the file/dataset).  If this is true, you want to pass`write_index=False` to the `to_parquet` call you showed above.
