### ISSUE TITLE
ValueError: Seek before start of file

### ISSUE THREAD

**Issue by MosheVai** [dask/fastparquet#508]
when appending to an existing data set there seems to be the expiation when trying to read it:

 <details>

```python
Traceback (most recent call last):
  File "D:\code\git_code\repo\venv\lib\site-packages\s3fs\core.py", line 530, in info
    Key=key, **version_id_kw(version_id), **self.req_kw)
  File "D:\code\git_code\repo\venv\lib\site-packages\s3fs\core.py", line 200, in _call_s3
    return method(**additional_kwargs)
  File "D:\code\git_code\repo\venv\lib\site-packages\botocore\client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "D:\code\git_code\repo\venv\lib\site-packages\botocore\client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\git_code\repo\venv\lib\site-packages\fastparquet\api.py", line 111, in __init__
    with open_with(fn2, 'rb') as f:
  File "D:\code\git_code\repo\venv\lib\site-packages\fsspec\spec.py", line 775, in open
    **kwargs
  File "D:\code\git_code\repo\venv\lib\site-packages\s3fs\core.py", line 378, in _open
    autocommit=autocommit, requester_pays=requester_pays)
  File "D:\code\git_code\repo\venv\lib\site-packages\s3fs\core.py", line 1097, in __init__
    cache_type=cache_type)
  File "D:\code\git_code\repo\venv\lib\site-packages\fsspec\spec.py", line 1065, in __init__
    self.details = fs.info(path)
  File "D:\code\git_code\repo\venv\lib\site-packages\s3fs\core.py", line 546, in info
    return super(S3FileSystem, self).info(path)
  File "D:\code\git_code\repo\venv\lib\site-packages\fsspec\spec.py", line 552, in info
    raise FileNotFoundError(path)
FileNotFoundError: my-bucket/example/d=2018-01-01 00:00:00/_metadata

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\code\git_code\repo\venv\lib\site-packages\fastparquet\api.py", line 117, in __init__
    self._parse_header(f, verify)
  File "D:\code\git_code\repo\venv\lib\site-packages\fastparquet\api.py", line 127, in _parse_header
    f.seek(-8, 2)
  File "D:\code\git_code\repo\venv\lib\site-packages\fsspec\spec.py", line 1134, in seek
    raise ValueError("Seek before start of file")
ValueError: Seek before start of file
```
</details>

```python
for date in ['2018-01-01', '2019-01-01']:
    print(f'upload {date}')
    df = pd.DataFrame({'d': pd.date_range(date, periods=5, freq='d'), 'n': list(range(5))})
    ddf = dd.from_pandas(df, npartitions=1)
    ddf.to_parquet('s3://my-bucket/example', partition_on=['d'],
                   engine='fastparquet', append=True, write_index=False,  write_metadata_file=False)

df = dd.read_parquet('s3://my-bucket/example').compute()  # <- this is where the exception in
```

Not sure if this is a fastparquet issue

**Environment**:

- Dask version: 2.20.0
- Python version:  3.7.6
- Operating System: windows
- Install method (conda, pip, source): pip - dask[complete]

**Comment by martindurant** [comment]
Sorry, I have not had a chance to look at this. Do you have any more information on what you think might be going on? With the code snippet as written, I think I would expect the second write to simply clobber the first. It may be that the s3 directory cache still contains the original file-size at this point (would be solved by `S3FileSystem().invalidate_cache()`).

**Comment by eason9** [comment]
I am running into a similar issue. If I run,

`s3.invalidate_cache()`
`s3_location = f"s3://{bucket}/{prefix}*.parquet"`
`df = dd.read_parquet(s3_location)`

Everything works fine.  But if I run the same code again without resetting my kernel it breaks with:

ParquetExeception: File parse failed: s3://<bucket_name>/<prefix>/*0001_part_00.parquet

**Comment by yohplala** [comment]
Hi @MosheVai 
As indicated by @martindurant 
'With the code snippet as written, I think I would expect the second write to simply clobber the first.'

More exactly this line in your code:
`ddf.to_parquet('s3://my-bucket/example', partition_on=['d'],
                   engine='fastparquet', write_index=False,  write_metadata_file=False)`
should be
`ddf.to_parquet('s3://my-bucket/example', partition_on=['d'],
                   engine='fastparquet', write_index=False,  write_metadata_file=False, append=True)`
to ensure appending.

Does using the `append` parameter help you?

You indicate:
'** EDIT ** I found a solution to my problem (don't know if this solves the original issue), it looks like there were some problems with boto3 and fastparquet in a recent version. I updated these and everything works like it should WITH s3.invalidate_cache() as suggested by @martindurant.'
Does this mean that you don't get error message?
But if you check your data, is ALL the data you expect still here or is it only the last data that you added in your last call?

**Comment by yohplala** [comment]
I just got a look at Dask API documentation, `to_parquet` [here](https://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.DataFrame.to_parquet).

It states that by default, it does not append.

'append:bool, optional
If False (default), construct data-set from scratch. [...]'

**Comment by eason9** [comment]
Hey @yohplala,

So my issue was different but realted to @MosheVai's,.  In my code my intention was to overwrite, hence I did not use `append`.

That being said, for what I am doing my current solution is to just turn caching off at the outset 

`s3fs.S3FileSystem.cachable = False`

and then make sure I explicitly provide my credentials (otherwise boto3 will literally randomly lose them . . . a current issue between fastparquet and boto3 I assume).

`df = dd.readparquet(s3_location, storage_options={'key':<key here>, 'secret':<secret here>, 'token':<token here>}, **kwargs)`

**Comment by suyeshShres** [comment]
market_album_df.to_parquet(path=s3 path,
                                   compression="snappy",
                                   append=True,
                                   ignore_divisions=True,
                                   storage_options={
                                       "key": config.all_properties["properties"]["aws_access_key_id"],
                                       "secret": config.all_properties["properties"]["aws_secret_access_key"]
                                   }
                                   )
I'm getting FileNotFoundError: when I'm trying to append the data in s3 bucket
