### ISSUE TITLE
write to common metadata fall with error: struct.error: 'i' format requires -2147483648 <= number <= 2147483647

### ISSUE THREAD

**Issue by PavelD0770** [dask/fastparquet#518]
**What happened**: I read big table (158 000 rows and 342GB total size) with partioned sql request to pandas DataFrame and write it to parquet files (dataset). After success parquet files writing, I try to write metadata files:
```
code fragment from my Python function:
...............
        for rows, sql_dt in table_data:
            # Пишем Parquet файл через fastparquet
            if pq_engine == 'fastparquet':
                row_size = wbytes/ch_nrows
                row_group_offsets = int(
                    round((use_memory_in_mb << 20)/row_size)) or 1
                # min(int(
                #     round((use_memory_in_mb << 20)/row_size)), ch_nrows)

                fp.write(fpath, rows, compression='GZIP',
                         row_group_offsets=row_group_offsets)
                flist.append(fpath)
..................
        # fastparquet metadata
        if pq_engine == 'fastparquet' and flist:
            fp.writer.merge(flist, verify_schema=True, root=tdir)

...............
```
where:  flist - list of parquet files in the dataset; root - path to directory with "flist"
result: write to "_metadata" - success; write to "_common_metadata" - error;
traceback:
``` 
Traceback (most recent call last):59023 (345) стр.; 324.16 ГБ; (733.65 МБ); время 41.4 с.; sql 8.826 с.; преобр. 0.004 c.; parquet 41.391 с.; rg_offsets=120
  File "projects/meta/meta.py", line 270, in <module>
    main(sys.argv[1:])
  File "projects/meta/meta.py", line 200, in main
    **pq_engine
  File "/home/airflow/projects/meta/metadata_functions/get_data_db.py", line 761, in db_data_loader
    fmt=fmt, pq_engine=pq_engine, data_dir=data_dir, multi_threading=False)
  File "/home/airflow/projects/meta/metadata_functions/get_data_db.py", line 640, in data_flow
    use_memory_in_mb=use_memory_in_mb, data_dir=data_dir)
  File "/home/airflow/projects/meta/metadata_functions/get_data_db.py", line 601, in table_loader_parquet
    fp.writer.merge(flist, verify_schema=True, root=tdir)
  File "/home/airflow/venv/lib/python3.7/site-packages/fastparquet/writer.py", line 1061, in merge
    write_common_metadata(out_file, fmd, open_with, no_row_groups=False)
  File "/home/airflow/venv/lib/python3.7/site-packages/fastparquet/writer.py", line 1007, in write_common_metadata
    f.write(struct.pack(b"<i", foot_size))
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
 ```

**What you expected to happen**: additional file  "_common_metadata" in the "root" directory 

I think, problem in next (for me)):
```python: /fastparquet/writer.py write_common_metadata
f.write(struct.pack(b"<i", foot_size))
```

**Anything else we need to know?**:

**Environment**:

- Dask version: -
- fastparquet version: 0.4.1 
- Python version: 3.7.4
- Operating System: Ubuntu 18.04 (64-bit, 20 logical core, 189GB RAM)
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
I do not have an immediate suggestion for you - the fastparquet package does not get much attention these days.
I do find it very odd, because the _common_metadata file is the same as the _metadata file, but without the row-group definitions. I suggest using `pdb` to figure out the difference between what is being written to the two files.
Note that, having the _metadata file, you don't really need the other one anyway.

Do you ever have `row_group_offsets=1`? That doesn't seem like a good idea.

**Comment by PavelD0770** [comment]
Thanks for your response. We use our solution for load big data to the datalake from various DBMS, various structures, data type. And fastparquet (before pyarrow 1.0 release) slightly better works with conversions of some data types. Therefore fastparquet we used by default. Now fastparquet and pyarrow converts same data types with same result in our cases, except time intervals (ns). We have 2 implementation: for fasparquet and for pyarrow. And solution for my problem not so critical by time for us.
Yes, I understand, difference between _comon_metadata and _metadata only in row groups statistics. Probably, into variable passed big value of written bytes  in foot_size = write_thrift(f, fmd), and next call f.write(struct.pack(b"<i", foot_size)) raised error?
Later, I will try to debug this case, but it will so slowly, because data is too big.
About two metadata files. I use the merge function from write.py, which writes _metadata and _common_metadata without alternative choices. I saw it in examples from github, I saw in fastparquet code, that I can use write_common_metadata directly, isn't it? 
No, I don't have ever  row_group_offsets=1. 
Best regards, Pavel
p.s. sorry for my English)

**Comment by martindurant** [comment]
> foot_size = write_thrift(f, fmd), and next call f.write(struct.pack(b"<i", foot_size)) raised error?

Agreed, but this number should always be smaller in _common_metadata than in _metadata

Yes, you could write your own merge function, since it isn't too complicated, but it really shouldn't be necessary.

**Comment by GitKalo** [comment]
Was this issue ever resolved? Getting a similar error -- @martindurant you said it could be due to having `row_group_offsets=1`?

**Comment by martindurant** [comment]
I did not manage to reproduce this. If you can post code that causes the problem, it will be much easier for us to fix.

**Comment by prafiny** [comment]
Having the same problem using pandas wrapping function when appending many rows:
```python
for i in range(300000000):
    df = pandas.from_dict{'col1': [i]}
    df.to_parquet(
                    'some_path',
                    engine='fastparquet',
                    append=True
                )
```

**Comment by martindurant** [comment]
parquet is now a row-store - it can save massive amounts of data, but has a limited number of "chunks". The highest number of chunks you will see in practical use is thousands, not 300M. I think you are hitting the limit on the size of the metadata area, which is stored in a 4-byte value, hence the error you see. Now, it may be that this should be an unsigned value, so you could have a metadata area twice the given size, but what you are doing here is still a *bad idea* and not what the parquet format was designed for.
