### ISSUE TITLE
Issue installing fastparquet using pip

### ISSUE THREAD

**Issue by Avi-Kamath** [dask/fastparquet#564]
While trying to install fastparquet using pip, I am getting the following error:
`pip install fastparquet`

```
Using cached fastparquet-0.5.0.tar.gz (120 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\XXXXX\.venv\scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\XXXXXX\\AppData\\Local\\Temp\\pip-install-4cym9llh\\fastparquet_2f3e573bba38407998337ad3a8c67c95\\setup.py'"'"'; __file__='"'"'C:\\Users\\XXXX\\AppData\\Local\\Temp\\pip-install-4cym9llh\\fastparquet_2f3e573bba38407998337ad3a8c67c95\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\XXXX\AppData\Local\Temp\pip-pip-egg-info-vmhd656k'
         cwd: C:\Users\XXXXX\AppData\Local\Temp\pip-install-4cym9llh\fastparquet_2f3e573bba38407998337ad3a8c67c95\
    Complete output (95 lines):
    Processing numpy/random\_bounded_integers.pxd.in
    Processing numpy/random\bit_generator.pyx
    Traceback (most recent call last):
      File "C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\tools\cythonize.py", line 59, in process_pyx
        from Cython.Compiler.Version import version as cython_version
    ModuleNotFoundError: No module named 'Cython'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\tools\cythonize.py", line 235, in <module>
        main()
      File "C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\tools\cythonize.py", line 231, in main
        find_process_files(root_dir)
      File "C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\tools\cythonize.py", line 222, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\tools\cythonize.py", line 188, in process
        processor_function(fromfile, tofile)
      File "C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\tools\cythonize.py", line 64, in process_pyx
        raise OSError('Cython needs to be installed in Python as a module')
    OSError: Cython needs to be installed in Python as a module
    Running from numpy source directory.
    C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\setup.py:485: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Traceback (most recent call last):
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\setup.py", line 513, in <module>
      File "C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\setup.py", line 493, in setup_package
      File "C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\setup.py", line 290, in generate_cython
    RuntimeError: Running cythonize failed!

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ XXXXX\AppData\Local\Temp\pip-install-4cym9llh\fastparquet_2f3e573bba38407998337ad3a8c67c95\setup.py", line 51, in <module>
        setup(
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
        raise
      File "C:\Users\ XXXXX\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "C:\Users\ XXXXX\AppData\Local\Programs\Python\Python38\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
        yield saved
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
        yield
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "c:\users\ XXXXX\desktop\dev\ XXXXXutilities\.venv\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\setup.py", line 513, in <module>
      File "C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\setup.py", line 493, in setup_package
      File "C:\Users\ XXXXX\AppData\Local\Temp\easy_install-8sg5uoz9\numpy-1.20.1\setup.py", line 290, in generate_cython
    RuntimeError: Running cythonize failed!
    Cythonizing sources
    ----------------------------------------
```

This error is due to cython not being installed and all I need to do is  install cython via pip. If there is a cython dependency for fastparquet why is it not included in requirements.txt? This creates an issue for me as whenever I try to bundle fastparquet as part of my package I need to ensure that cython is installed first. I tried adding cython to my setup.py, even then I have the same issue as fastparquet tries to install first and complains about cython not being available.

My list of installed packages:
Package    Version
---------- -------
pip        21.0.1
setuptools 41.2.0

Python version:
3.8.1 64 bit

Operating System
Windows 10

Install method
pip

**Comment by martindurant** [comment]
Whether or not you need cython depends on your installation method and previous packages - it is not a hard dependency, and you don't need it at runtime. Unfortunately, pip makes this hard to describe, which is why I generally recommend using conda.

**Comment by Avi-Kamath** [comment]
Thanks for the quick response. Being a bit green around python packing it took me a while to get it. As I understand pip cannot find the wheel it needs, it tries to build one using sdist and for this purpose you need cython. Having conda means I will directly access the wheel and if not the conda distribution already has the tool chain to build it. 

Is my understanding correct?

**Comment by martindurant** [comment]
Yes, except that conda *only* has a compiled/ready-to-use version, as the ecosystem has an explicit build step, e.g., see the conda-forge recipes, which in fastpraquet's case amounts to running `python setup.py` with a suitably declared environment (automatically repeated for each OS/python version) https://github.com/conda-forge/fastparquet-feedstock/blob/master/recipe/meta.yaml#L16

**Comment by Avi-Kamath** [comment]
Thank you. That's clears things up a lot.
