### ISSUE TITLE
Parsing an iso8601 date string with pandas throws 'ValueError' when writing parquet file using fastparquet

### ISSUE THREAD

**Issue by nikmartin** [dask/fastparquet#578]
**What happened**:
An error is thrown: 
```
 python dateTestCase.py 
{'id': ['8581d28b-c55c-4587-9a1e-2c83baa4a6ab'], 'site_name': ['TestString'], 'start_time': ['2021-01-01T14:58:19.3677242-05:00'], 'end_time': ['2021-01-01T14:59:50.5272973-05:00']}
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype                                 
---  ------      --------------  -----                                 
 0   id          1 non-null      object                                
 1   site_name   1 non-null      object                                
 2   start_time  1 non-null      datetime64[ns, pytz.FixedOffset(-300)]
 3   end_time    1 non-null      datetime64[ns, pytz.FixedOffset(-300)]
dtypes: datetime64[ns, pytz.FixedOffset(-300)](2), object(2)
memory usage: 160.0+ bytes
                                     id   site_name                          start_time                            end_time
0  8581d28b-c55c-4587-9a1e-2c83baa4a6ab  TestString 2021-01-01 14:58:19.367724200-05:00 2021-01-01 14:59:50.527297300-05:00
Traceback (most recent call last):
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/fastparquet/util.py", line 240, in get_column_metadata
    pd.Series([pd.to_datetime('now')]).dt.tz_localize(str(dtype.tz))
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/pandas/core/accessor.py", line 92, in f
    return self._delegate_method(name, *args, **kwargs)
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/pandas/core/indexes/accessors.py", line 109, in _delegate_method
    result = method(*args, **kwargs)
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py", line 250, in tz_localize
    arr = self._data.tz_localize(tz, ambiguous, nonexistent)
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 980, in tz_localize
    tz = timezones.maybe_get_tz(tz)
  File "pandas/_libs/tslibs/timezones.pyx", line 91, in pandas._libs.tslibs.timezones.maybe_get_tz
  File "pandas/_libs/tslibs/timezones.pyx", line 114, in pandas._libs.tslibs.timezones.maybe_get_tz
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'pytz.FixedOffset(-300)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dateTestCase.py", line 19, in <module>
    event_df.to_parquet('./{}.parquet'.format(event_id), compression='UNCOMPRESSED')
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/pandas/util/_decorators.py", line 199, in wrapper
    return func(*args, **kwargs)
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/pandas/core/frame.py", line 2455, in to_parquet
    return to_parquet(
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/pandas/io/parquet.py", line 390, in to_parquet
    impl.write(
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/pandas/io/parquet.py", line 279, in write
    self.api.write(
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/fastparquet/writer.py", line 933, in write
    fmd = make_metadata(data, has_nulls=has_nulls, ignore_columns=ignore,
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/fastparquet/writer.py", line 754, in make_metadata
    get_column_metadata(data[column], column))
  File "/home/nmartin/.local/share/virtualenvs/soe-etl-dPUxF-y4/lib/python3.8/site-packages/fastparquet/util.py", line 243, in get_column_metadata
    raise ValueError("Time-zone information could not be serialised: "
ValueError: Time-zone information could not be serialised: pytz.FixedOffset(-300), please use another
```

**What you expected to happen**:
The data frame to be written to the parquet file.

**Minimal Complete Verifiable Example**:

Minimal test case:
```python

import pandas as pd
import uuid
import dateutil.parser

event={}
event_id = str(uuid.uuid4())
event['id'] = [event_id]
event['site_name'] = ['TestString']
event['start_time'] = ['2021-01-01T14:58:19.3677242-05:00']
event['end_time'] = ['2021-01-01T14:59:50.5272973-05:00']
print(event)

event_df = pd.DataFrame(event)
event_df['start_time'] = pd.to_datetime(event_df['start_time'])
event_df['end_time'] = pd.to_datetime(event_df['end_time'])
event_df.info()
print(event_df)
event_df.to_parquet('./{}.parquet'.format(event_id), compression='uncompressed')
```

**Anything else we need to know?**:
If I switch to_parquet out for to_csv, the dataframe is written with no issues:
```csv
id,site_name,start_time,end_time
d0d58fe1-e2fc-4ba2-87e2-85b2548b8cef,InM_YFA_DAC1_Site_20201119,2021-01-01 14:58:19.367724200-05:00,2021-01-01 14:59:50.527297300-05:00
```

**Environment**:

- Dask version: 0.5.0
- Python version: 3.8
- Operating System: Ubuntu 20.04 Docker WSL/2 container 
- Install method (conda, pip, source): pipenv

**Comment by martindurant** [comment]
So it appears to be the line 
```
pd.Series([pd.to_datetime('now')]).dt.tz_localize(str(dtype.tz))
```
in `fastparquet.util.get_column_metadata`. What timezone do you have? I am thinking the line could be tinkered with to support a wider range of time zone styles.

**Comment by nikmartin** [comment]
> What timezone do you have? I am thinking the line could be tinkered with to support a wider range of time zone styles.

I'm not 100% sure of your question, but from the timestamp itself: `2021-01-01T14:58:19.3677242-05:00` the tz of **-05:00** is (as the error message also reports) -300 minutes, which is CDT

**Comment by nikmartin** [comment]
Also, the date string in the original test case ('2021-01-01T14:58:19.3677242-05:00') is pretty unremarkable as far as date strings go.  As far as I can tell, it's a textbook date string https://en.wikipedia.org/wiki/ISO_8601#Time_offsets_from_UTC

**Comment by martindurant** [comment]
Does pytz provide a method to get a string repr of a timezone, of the form that pandas can later understand? In this case, maybe it would indeed be "-05:00" or "-300". 

Note that this error exists because parquet only supports storing UTC times internally, so we are trying to store the time-zone information in text form in the metadata, so it can be recreated on load.

**Comment by nikmartin** [comment]
If this could be solved by me getting parsing the time in python first and just saving a timestamp,  I'm all for it. I don't necessarily need the tz info in my data, converting to UTC works.  For example, updating the test case to this:
 ```python
import pandas as pd
import uuid
import dateutil.parser

event={}
event_id = str(uuid.uuid4())
event['id'] = [event_id]
event['site_name'] = ['TestString']
event['start_time'] = ['2021-01-01T14:58:19.3677242-05:00']
event['end_time'] = ['2021-01-01T14:59:50.5272973-05:00']
print(event)

event_df = pd.DataFrame.from_dict(event)
event_df['start_time'] = pd.to_datetime(event_df['start_time'].astype('datetime64[ms]'))
event_df['end_time'] = pd.to_datetime(event_df['end_time'].astype('datetime64[ms]'))
event_df.info()
print(event_df)
event_df.to_parquet('./{}.parquet'.format(event_id), compression='uncompressed',index=False)
```
worked fine:
```
RangeIndex: 1 entries, 0 to 0
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   id          1 non-null      object        
 1   site_name   1 non-null      object        
 2   start_time  1 non-null      datetime64[ns]
 3   end_time    1 non-null      datetime64[ns]
dtypes: datetime64[ns](2), object(2)
memory usage: 160.0+ bytes
                                     id   site_name              start_time                end_time
0  2846c45c-00c2-4406-948a-2d30a47e017e  TestString 2021-01-01 19:58:19.367 2021-01-01 19:59:50.527
```

**Comment by martindurant** [comment]
> getting parsing the time in python first and just saving a timestamp

Sorry, what does this mean? Is that what your new code shows?

**Comment by nikmartin** [comment]
Sorry, no, the updated code does approximately the same thing using pandas.to_datetime, but the astype('datetime64[ms]') truncates the time to ms accuracy, and that seems to make everything work ok. to_datetime is the same as using python's datetime utils to parse a date string
