### ISSUE TITLE
Version 0.6.0: gcc: error: fastparquet/speedups.c: No such file or directory

### ISSUE THREAD

**Issue by Peque** [dask/fastparquet#598]
It seems `pip install fastparquet` fails with latest version. Hit this issue with some CI pipelines, but it seems it is easy to reproduce locally with Conda envs:

**What happened**:

```
$ conda create -n asdf python=3.8

$ conda activate asdf

(asdf) $ pip install fastparquet==0.6.0

Collecting fastparquet==0.6.0
  Using cached fastparquet-0.6.0.tar.gz (70 kB)
Collecting pandas>=1.1.0
  Downloading pandas-1.2.4-cp38-cp38-manylinux1_x86_64.whl (9.7 MB)
     |████████████████████████████████| 9.7 MB 3.9 MB/s 
Collecting numba>=0.49
  Using cached numba-0.53.1-cp38-cp38-manylinux2014_x86_64.whl (3.4 MB)
Collecting numpy>=1.11
  Using cached numpy-1.20.2-cp38-cp38-manylinux2010_x86_64.whl (15.4 MB)
Collecting thrift>=0.11.0
  Using cached thrift-0.13.0-cp38-cp38-linux_x86_64.whl
Collecting cramjam>=2.3.0
  Using cached cramjam-2.3.0-cp38-cp38-manylinux2010_x86_64.whl (1.4 MB)
Requirement already satisfied: setuptools in /cache/miniconda/envs/asdf/lib/python3.8/site-packages (from numba>=0.49->fastparquet==0.6.0) (52.0.0.post20210125)
Collecting llvmlite<0.37,>=0.36.0rc1
  Using cached llvmlite-0.36.0-cp38-cp38-manylinux2010_x86_64.whl (25.3 MB)
Collecting python-dateutil>=2.7.3
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2017.3
  Using cached pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: fastparquet
  Building wheel for fastparquet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /cache/miniconda/envs/asdf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-11xbyye0/fastparquet_cffe3e49744f46f6a1c645ac8cc2a225/setup.py'"'"'; __file__='"'"'/tmp/pip-install-11xbyye0/fastparquet_cffe3e49744f46f6a1c645ac8cc2a225/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-w32uhk53
       cwd: /tmp/pip-install-11xbyye0/fastparquet_cffe3e49744f46f6a1c645ac8cc2a225/
  Complete output (45 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/writer.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/util.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/thrift_structures.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/schema.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/encoding.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/dataframe.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/core.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/converted_types.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/compression.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/api.py -> build/lib.linux-x86_64-3.8/fastparquet
  copying fastparquet/__init__.py -> build/lib.linux-x86_64-3.8/fastparquet
  running egg_info
  writing fastparquet.egg-info/PKG-INFO
  writing dependency_links to fastparquet.egg-info/dependency_links.txt
  writing requirements to fastparquet.egg-info/requires.txt
  writing top-level names to fastparquet.egg-info/top_level.txt
  reading manifest file 'fastparquet.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'fastparquet/*.c'
  no previously-included directories found matching 'fastparquet/test/'
  no previously-included directories found matching 'test-data/'
  no previously-included directories found matching 'docs/'
  writing manifest file 'fastparquet.egg-info/SOURCES.txt'
  copying fastparquet/parquet.thrift -> build/lib.linux-x86_64-3.8/fastparquet
  creating build/lib.linux-x86_64-3.8/fastparquet/benchmarks
  copying fastparquet/benchmarks/columns.py -> build/lib.linux-x86_64-3.8/fastparquet/benchmarks
  creating build/lib.linux-x86_64-3.8/fastparquet/parquet_thrift
  copying fastparquet/parquet_thrift/__init__.py -> build/lib.linux-x86_64-3.8/fastparquet/parquet_thrift
  creating build/lib.linux-x86_64-3.8/fastparquet/parquet_thrift/parquet
  copying fastparquet/parquet_thrift/parquet/__init__.py -> build/lib.linux-x86_64-3.8/fastparquet/parquet_thrift/parquet
  copying fastparquet/parquet_thrift/parquet/constants.py -> build/lib.linux-x86_64-3.8/fastparquet/parquet_thrift/parquet
  copying fastparquet/parquet_thrift/parquet/ttypes.py -> build/lib.linux-x86_64-3.8/fastparquet/parquet_thrift/parquet
  running build_ext
  building 'fastparquet.speedups' extension
  creating build/temp.linux-x86_64-3.8
  creating build/temp.linux-x86_64-3.8/fastparquet
  gcc -pthread -B /cache/miniconda/envs/asdf/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/cache/miniconda/envs/asdf/include/python3.8 -I/tmp/pip-install-11xbyye0/fastparquet_cffe3e49744f46f6a1c645ac8cc2a225/.eggs/numpy-1.20.2-py3.8-linux-x86_64.egg/numpy/core/include -c fastparquet/speedups.c -o build/temp.linux-x86_64-3.8/fastparquet/speedups.o
  gcc: error: fastparquet/speedups.c: No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for fastparquet
  Running setup.py clean for fastparquet
Failed to build fastparquet
Installing collected packages: six, pytz, python-dateutil, numpy, llvmlite, thrift, pandas, numba, cramjam, fastparquet
    Running setup.py install for fastparquet ... error
    ERROR: Command errored out with exit status 1:
     command: /cache/miniconda/envs/asdf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-11xbyye0/fastparquet_cffe3e49744f46f6a1c645ac8cc2a225/setup.py'"'"'; __file__='"'"'/tmp/pip-install-11xbyye0/fastparquet_cffe3e49744f46f6a1c645ac8cc2a225/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4sklhgab/install-record.txt --single-version-externally-managed --compile --install-headers /cache/miniconda/envs/asdf/include/python3.8/fastparquet
         cwd: /tmp/pip-install-11xbyye0/fastparquet_cffe3e49744f46f6a1c645ac8cc2a225/
    Complete output (22 lines):
    running install
    running build
    running build_py
    running egg_info
    writing fastparquet.egg-info/PKG-INFO
    writing dependency_links to fastparquet.egg-info/dependency_links.txt
    writing requirements to fastparquet.egg-info/requires.txt
    writing top-level names to fastparquet.egg-info/top_level.txt
    reading manifest file 'fastparquet.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'fastparquet/*.c'
    no previously-included directories found matching 'fastparquet/test/'
    no previously-included directories found matching 'test-data/'
    no previously-included directories found matching 'docs/'
    writing manifest file 'fastparquet.egg-info/SOURCES.txt'
    running build_ext
    building 'fastparquet.speedups' extension
    creating build/temp.linux-x86_64-3.8
    creating build/temp.linux-x86_64-3.8/fastparquet
    gcc -pthread -B /cache/miniconda/envs/asdf/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/cache/miniconda/envs/asdf/include/python3.8 -I/cache/miniconda/envs/asdf/lib/python3.8/site-packages/numpy/core/include -c fastparquet/speedups.c -o build/temp.linux-x86_64-3.8/fastparquet/speedups.o
    gcc: error: fastparquet/speedups.c: No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /cache/miniconda/envs/asdf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-11xbyye0/fastparquet_cffe3e49744f46f6a1c645ac8cc2a225/setup.py'"'"'; __file__='"'"'/tmp/pip-install-11xbyye0/fastparquet_cffe3e49744f46f6a1c645ac8cc2a225/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-4sklhgab/install-record.txt --single-version-externally-managed --compile --install-headers /cache/miniconda/envs/asdf/include/python3.8/fastparquet Check the logs for full command output.
```

**Comment by martindurant** [comment]
I'm sorry - you will need cython and numpy installed to build. I'll push a correction.

**Comment by martindurant** [comment]
Alternatively, I can build the wheels for your system. What OS and python version are you running?

**Comment by zachary-jablons-okcupid** [comment]
I'm hitting this as well, and have `numpy` for sure but not as certain about Cython. Regardless, we've never encountered this issue before with prior fastparquet versions - is this a new requirement?

This is on Debian 8 with Python 3.7.5 (through `pyenv`), but we're also seeing it on Sagemaker containers.

**Comment by Peque** [comment]
@martindurant Sorry for not providing more information, thought it would be easier to reproduce.

- Python version is 3.8.8 (installed in a new fresh environment with Conda as it is shown in the first lines of the code block above)
- I am running Linux (Fedora 33 fully upgraded, 64 bits)

If I install NumPy and Cython:

```
$ conda create -n asdf python=3.8

$ conda activate asdf

(asdf) $ python --version
Python 3.8.8

(asdf) $ pip freeze | grep -i cython
Cython==0.29.23

(asdf) $ pip freeze | grep -i numpy
numpy==1.20.2

(asdf) $  pip install numpy cython

(asdf) $ pip install fastparquet==0.6.0
```

I still fails:

```
Collecting fastparquet==0.6.0
  Using cached fastparquet-0.6.0.tar.gz (70 kB)
Requirement already satisfied: pandas>=1.1.0 in /cache/miniconda/envs/asdf/lib/python3.8/site-packages (from fastparquet==0.6.0) (1.2.4)
Requirement already satisfied: numba>=0.49 in /cache/miniconda/envs/asdf/lib/python3.8/site-packages (from fastparquet==0.6.0) (0.53.1)
Requirement already satisfied: numpy>=1.11 in /cache/miniconda/envs/asdf/lib/python3.8/site-packages (from fastparquet==0.6.0) (1.20.2)
Requirement already satisfied: thrift>=0.11.0 in /cache/miniconda/envs/asdf/lib/python3.8/site-packages (from fastparquet==0.6.0) (0.13.0)
Requirement already satisfied: cramjam>=2.3.0 in /cache/miniconda/envs/asdf/lib/python3.8/site-packages (from fastparquet==0.6.0) (2.3.0)
Requirement already satisfied: llvmlite<0.37,>=0.36.0rc1 in /cache/miniconda/envs/asdf/lib/python3.8/site-packages (from numba>=0.49->fastparquet==0.6.0) (0.36.0)
Requirement already satisfied: setuptools in /cache/miniconda/envs/asdf/lib/python3.8/site-packages (from numba>=0.49->fastparquet==0.6.0) (52.0.0.post20210125)
Requirement already satisfied: pytz>=2017.3 in /cache/miniconda/envs/asdf/lib/python3.8/site-packages (from pandas>=1.1.0->fastparquet==0.6.0) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /cache/miniconda/envs/asdf/lib/python3.8/site-packages (from pandas>=1.1.0->fastparquet==0.6.0) (2.8.1)
Requirement already satisfied: six>=1.5 in /cache/miniconda/envs/asdf/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas>=1.1.0->fastparquet==0.6.0) (1.16.0)
Building wheels for collected packages: fastparquet
  Building wheel for fastparquet (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /cache/miniconda/envs/asdf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ioyotnto/fastparquet_e21883e5f9264f68823c76bc1a52f2b7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ioyotnto/fastparquet_e21883e5f9264f68823c76bc1a52f2b7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0yrmu0kq
       cwd: /tmp/pip-install-ioyotnto/fastparquet_e21883e5f9264f68823c76bc1a52f2b7/
  Complete output (11 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-ioyotnto/fastparquet_e21883e5f9264f68823c76bc1a52f2b7/setup.py", line 47, in <module>
      extra = {'ext_modules': cythonize(modules, language_level=3)}
    File "/cache/miniconda/envs/asdf/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 965, in cythonize
      module_list, module_metadata = create_extension_list(
    File "/cache/miniconda/envs/asdf/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
      for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
    File "/cache/miniconda/envs/asdf/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
      raise ValueError(error_msg)
  ValueError: 'fastparquet/speedups.pyx' doesn't match any files
  ----------------------------------------
  ERROR: Failed building wheel for fastparquet
  Running setup.py clean for fastparquet
Failed to build fastparquet
Installing collected packages: fastparquet
    Running setup.py install for fastparquet ... error
    ERROR: Command errored out with exit status 1:
     command: /cache/miniconda/envs/asdf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ioyotnto/fastparquet_e21883e5f9264f68823c76bc1a52f2b7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ioyotnto/fastparquet_e21883e5f9264f68823c76bc1a52f2b7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zwpqgv1x/install-record.txt --single-version-externally-managed --compile --install-headers /cache/miniconda/envs/asdf/include/python3.8/fastparquet
         cwd: /tmp/pip-install-ioyotnto/fastparquet_e21883e5f9264f68823c76bc1a52f2b7/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ioyotnto/fastparquet_e21883e5f9264f68823c76bc1a52f2b7/setup.py", line 47, in <module>
        extra = {'ext_modules': cythonize(modules, language_level=3)}
      File "/cache/miniconda/envs/asdf/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 965, in cythonize
        module_list, module_metadata = create_extension_list(
      File "/cache/miniconda/envs/asdf/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 815, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/cache/miniconda/envs/asdf/lib/python3.8/site-packages/Cython/Build/Dependencies.py", line 114, in nonempty
        raise ValueError(error_msg)
    ValueError: 'fastparquet/speedups.pyx' doesn't match any files
    ----------------------------------------
ERROR: Command errored out with exit status 1: /cache/miniconda/envs/asdf/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ioyotnto/fastparquet_e21883e5f9264f68823c76bc1a52f2b7/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ioyotnto/fastparquet_e21883e5f9264f68823c76bc1a52f2b7/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-zwpqgv1x/install-record.txt --single-version-externally-managed --compile --install-headers /cache/miniconda/envs/asdf/include/python3.8/fastparquet Check the logs for full command output.
```

**Comment by Peque** [comment]
PS: Just like @zachary-jablons-okcupid I also encountered this in a container (running Gitlab CI pipelines). Those run on Linux as well.

**Comment by martindurant** [comment]
Please try now. With any luck, you will get v0.6.0post1, which includes the C file in the source distribution while I figure out how to build wheels for everyone.

**Comment by zachary-jablons-okcupid** [comment]
Can confirm that `fastparquet-0.6.0.post1` builds fine

**Comment by Peque** [comment]
Thanks @martindurant ! `.post1` is building correctly for me too. And yeah, it would be great to have wheels available. :blush:

**Comment by JacobMaciejewski** [comment]
Indeed, ``` .post1 ``` is building correctly, but I am unable to import the library afterwards. I made a new issue #601. Are you able to reproduce the problem that I am having?

**Comment by martindurant** [comment]
Let's close this one, then, and continue discussion in the other issue, as needed. Thanks for the feedback, everyone. I would be happy for help on the "right" way to package fastprarquet for pip. 
Note that conda seems to do the right thing in all cases.

**Comment by Peque** [comment]
@martindurant Thanks for your help!

@JacobMaciejewski Unable to reproduce with a clean Python 3.8 environment created with Conda. :shrug:
