### ISSUE TITLE
Can't recover nullable strings when saving/loading a parquet file

### ISSUE THREAD

**Issue by ManuelZ** [dask/fastparquet#704]
I'm trying to save a Pandas DataFrame with nullable strings to a Parquet file, loading it back again and asserting that I get back the exact same DataFrame. Nullable string columns are getting back as "object" dtypes. I expect them to be "string" dtypes.

Minimally reproducible example:

```
import pandas as pd
from pandas._testing import assert_frame_equal

PARQUET_FILE = "temp.parquet"
ENGINE = "fastparquet"
schema = {
    "a": "string",
    "b": "Int64",
}

df = pd.DataFrame({
    "a": ["a", None],
    "b": [1, None],
}).astype(schema)

df.to_parquet(PARQUET_FILE, engine=ENGINE)
restored = pd.read_parquet(PARQUET_FILE, engine=ENGINE)
assert_frame_equal(df, restored, check_column_type=True)
print(f"\nBEFORE:\n{df}\nwith dtypes:\n{df.dtypes}\n\nAFTER:\n{restored}\nwith dtypes:\n{restored.dtypes}\n")
```

Output:

```
>>> assert_frame_equal(df, restored, check_column_type=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/manuel/.local/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 1308, in assert_frame_equal
    assert_series_equal(
  File "/home/manuel/.local/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 1002, in assert_series_equal
    assert_attr_equal("dtype", left, right, obj=f"Attributes of {obj}")
  File "/home/manuel/.local/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 501, in assert_attr_equal
    raise_assert_detail(obj, msg, left_attr, right_attr)
  File "/home/manuel/.local/lib/python3.8/site-packages/pandas/_testing/asserters.py", line 665, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Attributes of DataFrame.iloc[:, 0] (column name="a") are different

Attribute "dtype" are different
[left]:  string[python]
[right]: object
>>> print(f"\nBEFORE:\n{df}\nwith dtypes:\n{df.dtypes}\n\nAFTER:\n{restored}\nwith dtypes:\n{restored.dtypes}\n")

BEFORE:
      a     b
0     a     1
1  <NA>  <NA>
with dtypes:
a    string
b     Int64
dtype: object

AFTER:
      a     b
0     a     1
1  None  <NA>
with dtypes:
a    object
b     Int64
dtype: object


```

Python v3.8.10 on Ubuntu 20.04
Pandas v1.3.4
fastparquet installed from Git with: `pip install git+https://github.com/dask/fastparquet`

**Comment by martindurant** [comment]
Please see https://github.com/dask/fastparquet/issues/640 .

It would be possible to allow round-trip of String without making it the default on load, but whether it is default is another matter - we require fastparquet to work without arrow being present. However, a String column could be much more efficient to work with, especially if we implement DELTA_LENGTH_BYTE_ARRAY encoding (would be new cython code).
