### ISSUE TITLE
Multi-index fails in python 3.10

### ISSUE THREAD

**Issue by jeskowagner** [dask/fastparquet#737]
Thanks a lot for your work on fastparquet!

**What happened**:
Reading a parquet file containing a multi-index with dask does not work. The error thrown is possibly related to breaking changes introduced in Python 3.10, as mentioned [here](https://stackoverflow.com/a/70358664) the links contained in the answer. I should note that dask does not officially support multi-index, but work on this is [ongoing](https://github.com/dask/dask/issues/1493) and so looking into fixing the error described herein might be worthwhile, though not a high priority (unless it affects other structures in the same way).

**What you expected to happen**:
The Dataframe to read in with the multi-index retained. 

**Minimal Complete Verifiable Example**:
Partly taken from pandas documentation on [multi-index](https://pandas.pydata.org/pandas-docs/stable/user_guide/advanced.html)
```python
import numpy as np
import pandas as pd
import dask.dataframe as dd

# Create some data
arrays =
    ["bar", "bar", "baz", "baz", "foo", "foo", "qux", "qux"],
    ["one", "two", "one", "two", "one", "two", "one", "two"]
]
tuples = list(zip(*arrays))
index = pd.MultiIndex.from_tuples(tuples, names=["first", "second"])
s = pd.Series(np.random.randn(8), index=index)

# Convert to DataFrame and export
df = pd.DataFrame({"col1":s})
df.to_parquet("test.parq", engine="fastparquet")

# Import with dask to raise the error described
dd.read_parquet("test.parq", engine="fastparquet")

# Error log below, identifying information has been removed
```

```
Traceback (most recent call last):
  File "/path/to/env/g/lib/python3.10/site-packages/fastparquet/api.py", line 187, in _parse_header
    fmd = read_thrift(f, parquet_thrift.FileMetaData)
  File "/path/to/env/g/lib/python3.10/site-packages/fastparquet/thrift_structures.py", line 25, in read_thrift
    obj.read(pin)
  File "/path/to/env/g/lib/python3.10/site-packages/fastparquet/parquet_thrift/parquet/ttypes.py", line 4446, in read
    iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
    
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/env/g/lib/python3.10/site-packages/dask/dataframe/io/parquet/core.py", line 326, in read_parquet
    read_metadata_result = engine.read_metadata(
  File "/path/to/env/g/lib/python3.10/site-packages/dask/dataframe/io/parquet/fastparquet.py", line 855, in read_metadata
    dataset_info = cls._collect_dataset_info(
  File "/path/to/env/g/lib/python3.10/site-packages/dask/dataframe/io/parquet/fastparquet.py", line 461, in _collect_dataset_info
    pf = ParquetFile(paths[:1], open_with=fs.open, root=base, **kwargs)
  File "/path/to/env/g/lib/python3.10/site-packages/fastparquet/api.py", line 109, in __init__
    basepath, fmd = metadata_from_many(fn, verify_schema=verify,
  File "/path/to/env/g/lib/python3.10/site-packages/fastparquet/util.py", line 155, in metadata_from_many
    pfs = [api.ParquetFile(fn, open_with=open_with) for fn in file_list]
  File "/path/to/env/g/lib/python3.10/site-packages/fastparquet/util.py", line 155, in <listcomp>
    pfs = [api.ParquetFile(fn, open_with=open_with) for fn in file_list]
  File "/path/to/env/g/lib/python3.10/site-packages/fastparquet/api.py", line 133, in __init__
    self._parse_header(f, verify)
  File "/path/to/env/g/lib/python3.10/site-packages/fastparquet/api.py", line 189, in _parse_header
    raise ParquetException('Metadata parse failed: %s' % self.fn)
fastparquet.util.ParquetException: Metadata parse failed: /path/to/data/test.parq
```

**Environment**:

- Dask version: 2021.01.0
- Python version: 3.10.2
- Operating System: Scientific Linux 7.5 
- Install method (conda, pip, source): conda

**Anything else we need to know**:
Downgrading to python 3.7.12 with dask 2022.01.0 and fastparquet 0.7.2 fixes the problem. Also, with python=3.10.2, using engine="pyarrow" fixes the problem, suggesting that this problem is fastparquet-specific. Happy to troubleshoot more, if needed.

**Comment by martindurant** [comment]
This is a known failure for py310, and not specific to multi-indexes ( #736 ). The problem is gone in main, and just needs a release.

**Comment by jeskowagner** [comment]
Woops, sorry about that then! Thanks for your fast response.
