### ISSUE TITLE
python3.10 - SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

### ISSUE THREAD

**Issue by maulikamehta** [dask/fastparquet#756]
Seeing issue with Python 3.10 ( not with Python 3.8)

Traceback (most recent call last):
  File "/Users/locationqa/py3/lib/python3.10/site-packages/fastparquet/api.py", line 172, in _parse_header
    fmd = read_thrift(f, parquet_thrift.FileMetaData)
  File "/Users/locationqa/py3/lib/python3.10/site-packages/fastparquet/thrift_structures.py", line 25, in read_thrift
    obj.read(pin)
  File "/Users/locationqa/py3/lib/python3.10/site-packages/fastparquet/parquet_thrift/parquet/ttypes.py", line 1932, in read
    iprot._fast_decode(self, iprot, [self.__class__, self.thrift_spec])
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats

**Comment by martindurant** [comment]
This is an issue with thrift, unfortunately. 
V 0.8.0 of fastparquet no longer depends on thrift, so you shouldn't see a problem.
