### ISSUE TITLE
Error round-tripping timestamps with pyarrow

### ISSUE THREAD

**Issue by ian-r-rose** [dask/fastparquet#778]
:wave: I'm running into an issue where I'm unable to roundtrip some datetimes between pyarrow and fastparquet. It's probably something to do with conversion between `ms` and `ns` datetimes, but I didn't find a combination of args that work, and the defaults are running into troubles.

Oddly, the error doesn't seem to occur on the first time I round trip things, but it does on the second.

**Minimal Complete Verifiable Example**:

```python
import dask.datasets
import pandas as pd

df = dask.datasets.timeseries(freq="1H").repartition(npartitions=1).compute()   # some sample datetime data

df.to_parquet("test.parquet", engine="pyarrow")
pd.read_parquet("test.parquet", engine="fastparquet")  # succeeds

df.to_parquet("test.parquet", engine="pyarrow")
pd.read_parquet("test.parquet", engine="fastparquet")  # Fails?

```
produces
<details>
```
Traceback (most recent call last):
  File "parquet-datetime-issue.py", line 9, in <module>
    pd.read_parquet("test.parquet", engine="fastparquet")  # Fails?
  File "/home/ian/miniconda3/envs/dask/lib/python3.8/site-packages/pandas/io/parquet.py", line 493, in read_parquet
    return impl.read(
  File "/home/ian/miniconda3/envs/dask/lib/python3.8/site-packages/pandas/io/parquet.py", line 347, in read
    result = parquet_file.to_pandas(columns=columns, **kwargs)
  File "/home/ian/miniconda3/envs/dask/lib/python3.8/site-packages/fastparquet/api.py", line 734, in to_pandas
    df, views = self.pre_allocate(size, columns, categories, index)
  File "/home/ian/miniconda3/envs/dask/lib/python3.8/site-packages/fastparquet/api.py", line 760, in pre_allocate
    df, arrs = _pre_allocate(size, columns, categories, index, cats,
  File "/home/ian/miniconda3/envs/dask/lib/python3.8/site-packages/fastparquet/api.py", line 993, in _pre_allocate
    df, views = dataframe.empty(dtypes, size, cols=cols, index_names=index,
  File "/home/ian/miniconda3/envs/dask/lib/python3.8/site-packages/fastparquet/dataframe.py", line 142, in empty
    index = Index(d)
  File "/home/ian/miniconda3/envs/dask/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 453, in __new__
    result = klass(data, copy=copy, name=name, **kwargs)
  File "/home/ian/miniconda3/envs/dask/lib/python3.8/site-packages/pandas/core/indexes/datetimes.py", line 327, in __new__
    dtarr = DatetimeArray._from_sequence_not_strict(
  File "/home/ian/miniconda3/envs/dask/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 358, in _from_sequence_not_strict
    subarr, tz, inferred_freq = _sequence_to_dt64ns(
  File "/home/ian/miniconda3/envs/dask/lib/python3.8/site-packages/pandas/core/arrays/datetimes.py", line 2115, in _sequence_to_dt64ns
    data = conversion.ensure_datetime64ns(data)
  File "pandas/_libs/tslibs/conversion.pyx", line 257, in pandas._libs.tslibs.conversion.ensure_datetime64ns
  File "pandas/_libs/tslibs/np_datetime.pyx", line 120, in pandas._libs.tslibs.np_datetime.check_dts_bounds
pandas._libs.tslibs.np_datetime.OutOfBoundsDatetime: Out of bounds nanosecond timestamp: 15884-07-24 17:38:35
```
</details>

**Environment**:

- Dask version:  `main`
- Python version: 3.8.8
- Pandas version: 1.4.2
- Fastparquet version: 0.8.1
- Pyarrow version: 7.0
- Operating System: ubuntu
- Install method (conda, pip, source): pip

**Comment by ian-r-rose** [comment]
I looked into this a bit more, and here's what I understand to be happening:

fastparquet is pre-allocating memory for the pandas dataframe with the appropriate dtypes:
https://github.com/dask/fastparquet/blob/ad8c130c1244d813a4179df39afb04c12963b875/fastparquet/dataframe.py#L136

Depending on the vagaries of numpy allocator, it the data in the buffer *might* correspond to a valid timestamp, and it might not. So, for instance, I can make a snippet that fails with `np.full` to simulate an "empty" buffer that has a bad timestamp in it:

```python
import numpy
import pandas

# What if the `empty` buffer winds up with this data?
data = numpy.full(10, 2**64/3, dtype="datetime64[ms]")
pandas.Index(data)
```
