### ISSUE TITLE
KeyError: 'dir0' in partitioned dataset

### ISSUE THREAD

**Issue by nicornk** [dask/fastparquet#834]
**Describe the issue**:

**Minimal Complete Verifiable Example**:

```python
import pandas as pd
import os
import tempfile
import dask.dataframe as dd
from dask.distributed import Client

client = Client(
    n_workers=1, threads_per_worker=4, processes=True, memory_limit="2GB"
)

with tempfile.TemporaryDirectory() as tempdir:
    write_path = os.sep.join([tempdir, 'spark'])
    os.mkdir(write_path)

    pdf = pd.DataFrame(data={
        'Report_date': ['2011-03-15'],
        'Company': ['ACME Corp.']
    })

    pdf.to_parquet(write_path, partition_cols=['Report_date'])

    df = dd.read_parquet(
        tempdir,
        engine="fastparquet",
    ).get_partition(0)
    unique = df["Company"].unique().compute()
    print(unique)
    print(df.shape)
```

Exception Trace:
```
2022-12-21 10:52:38,955 - distributed.worker - WARNING - Compute Failed
Key:       ('read-parquet-bdc342c9134a4efa04729e9202d7324b', 0)
Function:  subgraph_callable-4eb4b919-a7fb-4e5f-9dd4-f7f3c7f7
args:      ({'piece': ('/var/folders/bz/fmx806z97pngw4f00n8fjh1m0000gn/T/tmp4t1zszts/spark/Report_date=2011-03-15/b41d59239ffd47dc8ce85b724ab69a59.parquet', None)})
kwargs:    {}
Exception: "KeyError('dir0')"

Traceback (most recent call last):
  File "tests/local_experiments/fastparquet-issue.py", line 41, in <module>
    unique = df["Company"].unique().compute()
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/dask/base.py", line 315, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/dask/base.py", line 600, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/distributed/client.py", line 3125, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/distributed/client.py", line 2294, in gather
    return self.sync(
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    return sync(
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/distributed/utils.py", line 406, in sync
    raise exc.with_traceback(tb)
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/distributed/utils.py", line 379, in f
    result = yield future
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/distributed/client.py", line 2157, in _gather
    raise exception.with_traceback(traceback)
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/dask/optimization.py", line 990, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 97, in __call__
    return read_parquet_part(
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 644, in read_parquet_part
    dfs = [
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/dask/dataframe/io/parquet/core.py", line 645, in <listcomp>
    func(
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/dask/dataframe/io/parquet/fastparquet.py", line 1005, in read_partition
    return cls.pf_to_pandas(
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/dask/dataframe/io/parquet/fastparquet.py", line 1045, in pf_to_pandas
    df, views = pf.pre_allocate(size, columns, categories, index)
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/fastparquet/api.py", line 791, in pre_allocate
    df, arrs = _pre_allocate(size, columns, categories, index, cats,
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/fastparquet/api.py", line 1028, in _pre_allocate
    dtypes = [get_type(c) for c in cols]
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/fastparquet/api.py", line 1028, in <listcomp>
    dtypes = [get_type(c) for c in cols]
  File "/Users/user/mambaforge/envs/jupyter/lib/python3.8/site-packages/fastparquet/api.py", line 1023, in get_type
    t = dt[name]
KeyError: 'dir0'


```

**Anything else we need to know?**:

Using `engine="pyarrow"` no exception is thrown and the output is:

```
0    ACME Corp.
Name: Company, dtype: object
(Delayed('int-cf205cd8-c266-4877-8a64-c8de10f0cf82'), 2)

```

**Environment**:

- Dask version: dask 2022.12.1 | fastparquet 2022.12.0 | distributed 2022.12.1
- Python version: Python 3.8.12 | packaged by conda-forge | (default, Sep 16 2021, 01:59:00)
- Operating System: macOS Ventura 13.0 (22A380)
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Just to note that this appears to work if
- you use the pandas or fastparquet API, not spark
- you use the actual root of the dataset, `write_path` rather than `tempdir`

So it's a bug in dask, or one could argue not a bug at all.

**Comment by nicornk** [comment]
Thanks for getting back so quickly - I was not sure if I should open the issue here or in the dask repo.

You know the codebase much better than me to conclude if this is a bug or not - at least it is an inconsistency that was annoying me to create this issue ;)

**Comment by martindurant** [comment]
I would say it is *not* strictly a bug. The behaviour is a result of giving the wrong directory path, one level higher than the actual root of the dataset. Specifically, when you partition on write, you get directories like "Report_date=value/" inside which the data files sit; this is the "hive" convention. When you then analyse a path like "spark/Report_date=value/part1.parq", it has a mix of this "hive" style information and non-hive part, and the exception is related to this apparent inconsistency. 

I think this can safely be closed.
