### ISSUE TITLE
Fails to rountrip non-`ns` `datetime64` with `pandas` 2.0

### ISSUE THREAD

**Issue by jrbourbeau** [dask/fastparquet#837]
While adding support in Dask for the upcoming `pandas=2.0` release, some of our unit tests began failing due to `fastparquet` no longer round-tripping `datetime64` data in the same way `pandas` does (or will in the `pandas=2.0` release).

Here's a minimal reproducer:

```python
import pandas as pd
from fastparquet import write, ParquetFile

df = pd.DataFrame({"x": [3, 2, 1]}).astype("M8[us]")
write("outfile.parq", df)
pf = ParquetFile("outfile.parq")
df2 = pf.to_pandas()
pd.testing.assert_frame_equal(df, df2)
```

which outputs 

```
Traceback (most recent call last):
  File "/Users/james/projects/dask/dask/test-fastparquet.py", line 8, in <module>
    pd.testing.assert_frame_equal(df, df2)
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/_testing/asserters.py", line 1200, in assert_frame_equal
    assert_series_equal(
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/_testing/asserters.py", line 907, in assert_series_equal
    assert_attr_equal("dtype", left, right, obj=f"Attributes of {obj}")
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/_testing/asserters.py", line 408, in assert_attr_equal
    raise_assert_detail(obj, msg, left_attr, right_attr)
  File "/Users/james/mambaforge/envs/dask/lib/python3.10/site-packages/pandas/_testing/asserters.py", line 592, in raise_assert_detail
    raise AssertionError(msg)
AssertionError: Attributes of DataFrame.iloc[:, 0] (column name="x") are different

Attribute "dtype" are different
[left]:  datetime64[us]
[right]: datetime64[ns]
```

My guess is this is related to this upcoming change in pandas https://pandas.pydata.org/docs/dev/whatsnew/v2.0.0.html#construction-with-datetime64-or-timedelta64-dtype-with-unsupported-resolution (though that's just a guess).

xref https://github.com/dask/dask/issues/9736

**Comment by martindurant** [comment]
Finally after all this time, pandas supports non-ns times! It has long seemed an oddity to me, given that numpy always did... 

I'll fix this soon and let you know. It will need some nasty `if version >= 2` blocks.

**Comment by martindurant** [comment]
What would be the best way to install pandas 2: clone the repo, or are there dev wheels somewhere?

**Comment by martindurant** [comment]
(nvm, following dask's CI workflow)
