### ISSUE TITLE
fastparquet 2023.1.0 may fail to dump dataframes with nested objects

### ISSUE THREAD

**Issue by GianlucaFicarelli** [dask/fastparquet#846]
**Describe the issue**:

fastparquet 2023.1.0 may fail with an exception when dumping pandas dataframes with nested objects

**Minimal Complete Verifiable Example**:

```python
import fastparquet
import numpy as np
import pandas as pd

df = pd.DataFrame({"A": np.array([[1.1, 1.2], [], None], dtype=object)})
df.to_parquet(path="/tmp/output.parquet", engine="fastparquet")
```

Result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/test/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/tmp/test/venv/lib/python3.9/site-packages/pandas/core/frame.py", line 2976, in to_parquet
    return to_parquet(
  File "/tmp/test/venv/lib/python3.9/site-packages/pandas/io/parquet.py", line 430, in to_parquet
    impl.write(
  File "/tmp/test/venv/lib/python3.9/site-packages/pandas/io/parquet.py", line 312, in write
    self.api.write(
  File "/tmp/test/venv/lib/python3.9/site-packages/fastparquet/writer.py", line 1291, in write
    fmd = make_metadata(data, has_nulls=has_nulls, ignore_columns=ignore,
  File "/tmp/test/venv/lib/python3.9/site-packages/fastparquet/writer.py", line 895, in make_metadata
    se, type = find_type(data[column], fixed_text=fixed,
  File "/tmp/test/venv/lib/python3.9/site-packages/fastparquet/writer.py", line 126, in find_type
    object_encoding = infer_object_encoding(data)
  File "/tmp/test/venv/lib/python3.9/site-packages/fastparquet/writer.py", line 343, in infer_object_encoding
    if pd.isna(i):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

```

**Anything else we need to know?**:

The same code works with fastparquet 2022.12.0

**Environment**:

- Dask version:
- Python version: 3.9.6
- Operating System: mac, linux
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
I can fix that! To work around it, please specify `object_encoding="JSON"` or `object_encoding={"A": "JSON"}`.

**Comment by GianlucaFicarelli** [comment]
Thanks @martindurant for the quick reply and the fix :)
