### ISSUE TITLE
AttributeError: 'ParquetFile' object has no attribute '_columns_dtype' when reading files without pandas metadata

### ISSUE THREAD

**Issue by piotrb5e3** [dask/fastparquet#869]
**Describe the issue**:
I'm getting the following crash when I try to open a parquet file that was created with either pyspark or pyarrow.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/piotr.bakalarski/repos/neural-search-commons/venv/lib/python3.10/site-packages/fastparquet/api.py", line 407, in iter_row_groups
    df = self[i].to_pandas(filters=filters, **kwargs)
  File "/Users/piotr.bakalarski/repos/neural-search-commons/venv/lib/python3.10/site-packages/fastparquet/api.py", line 765, in to_pandas
    df, views = self.pre_allocate(size, columns, categories, index, dtypes=dtypes)
  File "/Users/piotr.bakalarski/repos/neural-search-commons/venv/lib/python3.10/site-packages/fastparquet/api.py", line 796, in pre_allocate
    dtypes, self.tz, columns_dtype=self._columns_dtype)
AttributeError: 'ParquetFile' object has no attribute '_columns_dtype'
```

**Minimal Complete Verifiable Example**:

Using `fastparquet==2023.4.0` and `pyarrow==10.0.1`:

```python
import pyarrow.parquet as pq
import pyarrow as pa
from fastparquet import ParquetFile

pq.write_table(pa.table({"a": "abcd", "n": [1,2,3,4]}), "repro.parquet")
pf = ParquetFile("repro.parquet")

pf.head(1)  # <-- This line causes error
```

**Anything else we need to know?**:
From what I can see, this is caused by `_columns_dtype` not getting set, because the `__setstate__` in `__getitem__` [[HERE]](https://github.com/dask/fastparquet/blob/main/fastparquet/api.py#L318) does not set `_columns_dtype`. Overall it seems that this __getitem__ behavior is unintuitive and may lead to more issues with not-copied parameters.

**Environment**:

- Dask version: None
- Fastparquet version: 2023.4.0
- Python version: 3.10.11
- Operating System: macOS Ventura 13.4.1
- Install method (conda, pip, source): pip

**Comment by piotrb5e3** [comment]
I can see that this was already fixed in _Extra field when cloning ParquetFile (#866)_. Could you release a new version of the library?
