### ISSUE TITLE
row_filter=True fails if parquet file wasn't made by fastparquet

### ISSUE THREAD

**Issue by zmbc** [dask/fastparquet#873]
**Describe the issue**:

When reading a file with fastparquet, that was not written by fastparquet, row_filter=True causes an error:

```
Traceback (most recent call last):
  File ".../fastparquet_bug.py", line 11, in <module>
    assert pf.to_pandas(filters=[["b", "in", [1, 3, 4]]], row_filter=True).b.tolist() == [1, 3, 4]
  File ".../lib/python3.9/site-packages/fastparquet/api.py", line 783, in to_pandas
    self.read_row_group_file(rg, columns, categories, index,
  File ".../lib/python3.9/site-packages/fastparquet/api.py", line 385, in read_row_group_file
    core.read_row_group(
  File ".../lib/python3.9/site-packages/fastparquet/core.py", line 631, in read_row_group
    read_row_group_arrays(file, rg, columns, categories, schema_helper,
  File ".../lib/python3.9/site-packages/fastparquet/core.py", line 601, in read_row_group_arrays
    read_col(column, schema_helper, file, use_cat=name+'-catdef' in out,
  File ".../lib/python3.9/site-packages/fastparquet/core.py", line 517, in read_col
    val = val[row_filter[index_off:index_off+len(val)]]
TypeError: only integer scalar arrays can be converted to a scalar index
```

**Minimal Complete Verifiable Example**:

I created a fresh environment with python 3.9, then ran `pip install pandas fastparquet pyarrow`.

Then, I ran this script, which is exactly like [one of the fastparquet tests](https://github.com/dask/fastparquet/blob/574b061a33a0228ba0a5817476e594996d2eeb26/fastparquet/test/test_api.py#L1091-L1108), except that I perform the write-to-file step with pyarrow instead of fastparquet.

```python
from fastparquet import ParquetFile
import pandas as pd

df = pd.DataFrame({
    'a': ['o'] * 10 + ['i'] * 5,
    'b': range(15)
})
df.to_parquet('test.parquet', engine="pyarrow")

pf = ParquetFile('test.parquet')
assert pf.to_pandas(filters=[["b", "in", [1, 3, 4]]], row_filter=True).b.tolist() == [1, 3, 4]
```

It gives the error above.

**Anything else we need to know?**:

I did a bit of debugging and found this line:

https://github.com/dask/fastparquet/blob/574b061a33a0228ba0a5817476e594996d2eeb26/fastparquet/core.py#L159

This changes `values` from being a NumPy array to being a memoryview object.

Replacing that line with `values = np.array(values.data[:nval])` fixes the error. However, I don't understand what that line is doing well enough to know if that is a general solution or not.

**Environment**:

- Dask version: none
- Fastparquet version: 2023.7.0
- Python version: 3.9.16
- Operating System: Ubuntu 20.04.6
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Fix is in the linked PR. Sorry this took so long, and thank you for pointing out the problem line.
