### ISSUE TITLE
to_pandas(): cramjam.DecompressionError: snappy: output buffer (size = 262144) is smaller than required (size = 1048576)

### ISSUE THREAD

**Issue by miohtama** [dask/fastparquet#889]
**Describe the issue**:

Getting the following exception when trying to read a large Parquet file written with `PyArrow`:

```
Traceback (most recent call last):
  File "/Users/moo/code/ts/fastparquet-bugsies/fastparquet-decompression-error.py", line 23, in <module>
    df2 = pf2.to_pandas()
          ^^^^^^^^^^^^^^^
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/api.py", line 784, in to_pandas
    self.read_row_group_file(rg, columns, categories, index,
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/api.py", line 386, in read_row_group_file
    core.read_row_group(
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 632, in read_row_group
    read_row_group_arrays(file, rg, columns, categories, schema_helper,
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 602, in read_row_group_arrays
    read_col(column, schema_helper, file, use_cat=name+'-catdef' in out,
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 497, in read_col
    num += read_data_page_v2(infile, schema_helper, se, ph.data_page_header_v2, cmd,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 290, in read_data_page_v2
    decomp(np.frombuffer(infile.read(size), dtype="uint8"),
cramjam.DecompressionError: snappy: output buffer (size = 262144) is smaller than required (size = 1048576)
```

PyArrow reads the file fine.

**Minimal Complete Verifiable Example**:

[Find reproduction repo here](https://github.com/tradingstrategy-ai/fastparquet-reproduction).

500MB test file is distributed with Git LFS.

```python
from pyarrow import parquet as pq  # pyarrow 10
from fastparquet import ParquetFile  # fastparquet  2023.1.0

path = "./lending-reserves-all.parquet"

# PyArrow works
df1 = pq.read_table(path).to_pandas()

pf2 = ParquetFile(path)

# Will bomb out
#           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#  File "/Users/moo/Library/Caches/pypoetry/virtualenvs/fastparquet-bugsies-qrDtU46f-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 290, in read_data_page_v2
#    decomp(np.frombuffer(infile.read(size), dtype="uint8"),
# cramjam.DecompressionError: snappy: output buffer (size = 262144) is smaller than required (size = 1048576)

df2 = pf2.to_pandas()

```

**Environment**:

```
fastparquet     2023.8.0     Python support for Parquet file format
```

- Python version: Python 3.11.5
- Operating System: macOS
- Install method: Poetry

**Comment by martindurant** [comment]
Thanks you for providing the full set of steps to reproduce the issue
