### ISSUE TITLE
Can't read the parquet directory without _metadata file

### ISSUE THREAD

**Issue by bluszcz** [dask/fastparquet#89]
When I am trying to open directory with parquet files it crashes when *_metadata* file is not being found:

```
(lambda2) [ec2-user@ ~]$ cat start.py
#!/usr/bin/python
from fastparquet import ParquetFile
fn = "/home/ec2-user/parquet-gzip/"
#fn = "/home/ec2-user/parquet-gzip/part-00000-test-gz.parquet"
pf = ParquetFile(fn)
df = pf.to_pandas()
print (df)
(lambda2) [ec2-user@ ~]$ ls -lah parquet-gzip/
total 21M
drwxr-xr-x  2 ec2-user ec2-user 4.0K Feb 22 13:31 .
drwx------ 14 ec2-user ec2-user 4.0K Feb 22 13:34 ..
-rw-r--r--  1 ec2-user ec2-user  11M Feb 22 12:09 part-00000-test.gz.parquet
-rw-r--r--  1 ec2-user ec2-user  11M Feb 22 12:09 part-00001-test.gz.parquet
(lambda2) [ec2-user@ ~]$ python start.py
Traceback (most recent call last):
  File "start.py", line 5, in <module>
    pf = ParquetFile(fn)
  File "/home/ec2-user/lambda2/local/lib/python2.7/dist-packages/fastparquet/api.py", line 52, in __init__
    with open_with(fn, 'rb') as f:
  File "/home/ec2-user/lambda2/local/lib/python2.7/dist-packages/fastparquet/util.py", line 39, in default_open
    return open(f, mode)
IOError: [Errno 21] Is a directory: '/home/ec2-user/parquet-gzip/'
(lambda2) [ec2-user@ ~]$
```
Output from strace:
```
3741  open("/home/ec2-user/parquet-gzip//_metadata", O_RDONLY) = -1 ENOENT (No such file or directory)
```

Would it be difficult to implement support for directories without this file? After some research I suspect they are not obligatory:

https://forums.databricks.com/questions/6494/do-you-need-a-metadata-file-in-a-parquet-folder-to.html

**Comment by martindurant** [comment]
You could either read the pieces individually, or you could run the `merge()` function to build a metadata file from the pieces. I do not immediately have a plan to support a directory without metadata, because many configurations of sub-directories might exist.

**Comment by martindurant** [comment]
Closing in favour of #90, which has more discussion.
