### ISSUE TITLE
a python-3.12 windows wheel 

### ISSUE THREAD

**Issue by stonebig** [dask/fastparquet#892]
It woud be nice to have an official python-3.12 wheel

**Comment by martindurant** [comment]
This will happen at the next release. That can happen when #891 is fixed, hopefully soon.

**Comment by GadgetG** [comment]
Is release 2023.10.1 compatible with Python 3.12?

**Comment by GadgetG** [comment]
I tried to install it with pip, but got the error.
Collecting fastparquet
  Using cached fastparquet-2023.10.1.tar.gz (393 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [28 lines of output]
      Traceback (most recent call last):
        File "C:\Users\gaohu\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\gaohu\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gaohu\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gaohu\AppData\Local\Temp\pip-build-env-rx_85ywh\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gaohu\AppData\Local\Temp\pip-build-env-rx_85ywh\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\gaohu\AppData\Local\Temp\pip-build-env-rx_85ywh\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\gaohu\AppData\Local\Temp\pip-build-env-rx_85ywh\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 47, in <module>
        File "C:\Users\gaohu\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gaohu\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\gaohu\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by martindurant** [comment]
I don't know why the py3.12 windows wheel didn't build :|
To compile locally, you would need cython and a full C- compiler toolchain.

**Comment by stonebig** [comment]
`pip install git+https://github.com/dask/fastparquet` works on Windows  python-3.12.1 ... maybe it was one of the 400 fixes  since Python-3.12.0 ?

**Comment by martindurant** [comment]
I may do a release in the next couple of weeks, and we'll see if cibuild will now make the right wheels.

**Comment by stonebig** [comment]
a last try ?

**Comment by martindurant** [comment]
OK, looks like it's going to work. https://github.com/dask/fastparquet/actions/runs/7805752044

I'll trigger it tomorrow.

**Comment by martindurant** [comment]
done

**Comment by stonebig** [comment]
hum ... I don't see a python-3.12 windows wheel at pypi arrival, yet https://pypi.org/project/fastparquet/2024.2.0/#files

**Comment by martindurant** [comment]
I am at a loss :|.  linux/darwin built OK. Maybe I'll need to build it by hand on a windows box.

**Comment by martindurant** [comment]
Try now?

**Comment by GadgetG** [comment]
It works now, thank you.
