### ISSUE TITLE
Nullable types for 1 row vs multiple rows

### ISSUE THREAD

**Issue by yoav-orca** [dask/fastparquet#901]
**Describe the issue**:
When exporting a parquet file with a single row, the library fails to convert the nullable int32 to a nullable pandas type and fails with the following error.
```
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NAType'
```

**Minimal Complete Verifiable Example**:

```python
import base64
from io import BytesIO

from fastparquet import ParquetFile

two_rows_file = "UEFSMRUAFSwVMCwVBBUAFQYVBhwAAAAWVAIAAAAEAQQAAAB2YWwxBAAAAHZhbDIVABUMFRAsFQQVABUGFQYcNgIAAAAGFAIAAAAEABkRAhkYABkYABUAABkRAhkYABkYABUAABkcFggVMBYAAAAZHBZeFRAWAAAAFQIZPDUAGA9wYXJxdWV0X2dvX3Jvb3QVBAAVDBUAFQIYBGNvbDE1ABUAFQAAFQIVABUCGARjb2wyJSIVABUAFQAcrBMgEQAAABYEGRwZLCYIHBUMGTUGCAAZGARjb2wxFQIWBBZSFlYmCDwAABbIARUUFpgBFRgAJl4cFQIZNQYIABkYBGNvbDIVAhYEFjYWOiZePDYCAAAW3AEVFBawARUYABaIARYEAACqAAAAUEFSMQ=="
single_row_file = "UEFSMRUAFRwVICwVAhUAFQYVBhwAAAAONAIAAAACAQQAAAB2YWwxFQAVDBUQLBUCFQAVBhUGHDYAAAAABhQCAAAAAgAZEQIZGAAZGAAVAAAZEQIZGAAZGAAVAAAZHBYIFSAWAAAAGRwWThUQFgAAABUCGTw1ABgPcGFycXVldF9nb19yb290FQQAFQwVABUCGARjb2wxNQAVABUAABUCFQAVAhgEY29sMiUiFQAVABUAHKwTIBEAAAAWAhkcGSwmCBwVDBk1BggAGRgEY29sMRUCFgIWQhZGJgg8AAAWuAEVFBaIARUYACZOHBUCGTUGCAAZGARjb2wyFQIWAhY2FjomTjw2AAAAFswBFRQWoAEVGAAWeBYCAACpAAAAUEFSMQ=="

data1 = BytesIO(base64.b64decode(two_rows_file))
data2 = BytesIO(base64.b64decode(single_row_file))

# multiple rows
f1 = ParquetFile(data1)
print(f1)
print(f1.dtypes)
print(f1.head(1))

# single row
f2 = ParquetFile(data2)
print(f2)
print(f2.dtypes)
print(f2.head(1))
```
The above code produces the following:
```
<Parquet File: {'name': None, 'columns': ['col1', 'col2'], 'partitions': [], 'rows': 2, 'row_groups': 1}>
OrderedDict([('col1', dtype('O')), ('col2', Int32Dtype())])
      col1  col2
0  b'val1'  <NA>
<Parquet File: {'name': None, 'columns': ['col1', 'col2'], 'partitions': [], 'rows': 1, 'row_groups': 1}>
OrderedDict([('col1', dtype('O')), ('col2', dtype('int32'))])
Traceback (most recent call last):
  File "/home/ubuntu/src/bug.py", line 20, in <module>
    print(f2.head(1))
          ^^^^^^^^^^
  File "/home/ubuntu/Library/Caches/pypoetry/virtualenvs/fastparquet-d-zUpOTr-py3.11/lib/python3.11/site-packages/fastparquet/api.py", line 308, in head
    return self[:i+1].to_pandas(**kwargs).head(nrows)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/Library/Caches/pypoetry/virtualenvs/fastparquet-d-zUpOTr-py3.11/lib/python3.11/site-packages/fastparquet/api.py", line 784, in to_pandas
    self.read_row_group_file(rg, columns, categories, index,
  File "/home/ubuntu/Library/Caches/pypoetry/virtualenvs/fastparquet-d-zUpOTr-py3.11/lib/python3.11/site-packages/fastparquet/api.py", line 386, in read_row_group_file
    core.read_row_group(
  File "/home/ubuntu/Library/Caches/pypoetry/virtualenvs/fastparquet-d-zUpOTr-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 642, in read_row_group
    read_row_group_arrays(file, rg, columns, categories, schema_helper,
  File "/home/ubuntu/Library/Caches/pypoetry/virtualenvs/fastparquet-d-zUpOTr-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 612, in read_row_group_arrays
    read_col(column, schema_helper, file, use_cat=name+'-catdef' in out,
  File "/home/ubuntu/Library/Caches/pypoetry/virtualenvs/fastparquet-d-zUpOTr-py3.11/lib/python3.11/site-packages/fastparquet/core.py", line 558, in read_col
    part[defi != max_defi] = my_nan
    ~~~~^^^^^^^^^^^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NAType'

```

**Anything else we need to know?**:
The same input file with the same schema behaves differently if there is only one row or two rows.

**Environment**:

- Dask version: N/A, fastparquet version `2023.10.1`
- Python version: 3.11
- Operating System: macOS 14.0 / Ubuntu 22.04
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
Thank you for providing your data inline - an ingenious solution! 

I notice that examining `pf2.row_groups[0]`, I see
```
...
     statistics:
       distinct_count: null
       max: null
       max_value: null
       min: null
       min_value: null
       null_count: 0
```
i.e., the matadata claims there should be no null values in the file, but in fact there is one. How was this data created?

**Comment by yoav-orca** [comment]
@martindurant I overlooked the null_count.
I'm using SingleStore to export parquet; apparently, the bug is there.

**Comment by martindurant** [comment]
I did wonder, since the created_by field was blank. If you file an issue with them, please link here.
