### ISSUE TITLE
Fastparquet raises on import with numpy 2.0 rc

### ISSUE THREAD

**Issue by phofl** [dask/fastparquet#923]
**Describe the issue**:

```
>>> import fastparquet

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0rc1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<stdin>", line 1, in <module>
  File "/Users/patrick/mambaforge/envs/fastparquet/lib/python3.11/site-packages/fastparquet/__init__.py", line 4, in <module>
    from fastparquet.writer import write, update_file_custom_metadata
  File "/Users/patrick/mambaforge/envs/fastparquet/lib/python3.11/site-packages/fastparquet/writer.py", line 15, in <module>
    from fastparquet.api import ParquetFile, partitions, part_ids
  File "/Users/patrick/mambaforge/envs/fastparquet/lib/python3.11/site-packages/fastparquet/api.py", line 11, in <module>
    from fastparquet import core, schema, converted_types, encoding, dataframe, writer
  File "/Users/patrick/mambaforge/envs/fastparquet/lib/python3.11/site-packages/fastparquet/core.py", line 4, in <module>
    from fastparquet import encoding
  File "/Users/patrick/mambaforge/envs/fastparquet/lib/python3.11/site-packages/fastparquet/encoding.py", line 4, in <module>
    from fastparquet.speedups import unpack_byte_array
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/patrick/mambaforge/envs/fastparquet/lib/python3.11/site-packages/fastparquet/__init__.py", line 4, in <module>
    from fastparquet.writer import write, update_file_custom_metadata
  File "/Users/patrick/mambaforge/envs/fastparquet/lib/python3.11/site-packages/fastparquet/writer.py", line 15, in <module>
    from fastparquet.api import ParquetFile, partitions, part_ids
  File "/Users/patrick/mambaforge/envs/fastparquet/lib/python3.11/site-packages/fastparquet/api.py", line 11, in <module>
    from fastparquet import core, schema, converted_types, encoding, dataframe, writer
  File "/Users/patrick/mambaforge/envs/fastparquet/lib/python3.11/site-packages/fastparquet/core.py", line 4, in <module>
    from fastparquet import encoding
  File "/Users/patrick/mambaforge/envs/fastparquet/lib/python3.11/site-packages/fastparquet/encoding.py", line 4, in <module>
    from fastparquet.speedups import unpack_byte_array
  File "fastparquet/speedups.pyx", line 1, in init fastparquet.speedups
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).

```

**Minimal Complete Verifiable Example**:

```python
mamba create -n fastparquet python=3.11
mamba activate fastparquet
pip install "numpy==2.0.0rc1"
pip install fastparquet

import fastparquet
```

**Anything else we need to know?**:

**Environment**:

- Dask version:
- Python version: 3.11
- Operating System: Mac
- Install method (conda, pip, source): pip

**Comment by martindurant** [comment]
I also saw this when trying to investigate #921 .

We *might* need to wait for a conda-ready numpy 2 and dependencies like pandas.

@bnavigator , how did you manage to build fastparquet and run the tests?
- A naive pip-install of pandas does not get numpy 2
- force-installing 2.0.0rc1 brings about the error mentioned in this thread, and 
- following the instructions to call `import_array()` resulted in a the dreaded "size of dtype changed" exception.

**Comment by martindurant** [comment]
Ah
```
-        'oldest-supported-numpy'
```
of course ...

**Comment by martindurant** [comment]
Thanks, @bnavigator , I can build and run the test suite like that and see the failures you fixed in the other PR (I still get warnings on import). 

Is, then, the recommendation to build a new set of wheels for release built with the rc1, and expect these should work with older numpy too?

**Comment by bnavigator** [comment]
> Is, then, the recommendation to build a new set of wheels for release built with the rc1, and expect these should work with older numpy too?

Exactly: https://numpy.org/devdocs/dev/depending_on_numpy.html#numpy-2-0-specific-advice
